### ISSUE TITLE
TCP connection not work

### ISSUE THREAD

**Issue by zerobias** [zerobias/telegram-mtproto#1]

**Comment by wfjsw** [comment]
I thought TCP is better coz server can push response instead of client polling.

**Comment by zerobias** [comment]
@wfjsw I understand, but it requires changes very deep in network layer, and unfortunately I just don't have time to this

**Comment by JackPoteYes** [comment]
Is there any plan to implement this feature now ?
It  ould certainly be useful, as one of the main features of Telegram's API.

**Comment by zerobias** [comment]
@JackPoteYes Yes, I'll implement this feature after project reaches beta

**Comment by JackPoteYes** [comment]
What a good news. When are you launching the beta ?

**Comment by goodmind** [comment]
![image](https://user-images.githubusercontent.com/3275424/30595700-5bb39a8c-9d6b-11e7-95ba-e0428a97d8c2.png)

**Comment by moltar** [comment]
I'm putting up a bounty of USD$100 on this, paid out in crypto.

I want to be able to listen to Telegram messages using websockets (or similar) and get instant callback when a message arrives, without having to poll the API every second.

Thanks.

**Comment by JackPoteYes** [comment]
@moltar I've found a potential solution since then, with another language though.
Contact me on fb @guilhem fry for more info.
No bounty needed.
Will delete this message in a couple of days

**Comment by moltar** [comment]
@JackPoteYes Not sure what your fb is... Please post a full link or name. Thanks.
