### ISSUE TITLE
How to update Schemas?

### ISSUE THREAD

**Issue by DenisIzmaylov** [zerobias/telegram-mtproto#10]
I've found a few data files in the repo.

+ https://github.com/zerobias/telegram-mtproto/tree/mtproto2/schema

How we could update it? Is there some step-by-step instruction?

**Comment by zerobias** [comment]
The custom schema can be set as _schema_ field on ApiManager constructor.
Mtproto schema setted at _mtSchema_ field.
E.g.
```javascript
const apiSchema = require('./api-57.json')
const mtSchema = require('./mtproto-57.json')

new ApiManager({ schema: apiSchema, mtSchema: mtSchema })
```

Or, it may be better to make a common field for the scheme?
```javascript

const schema57 = {
  api: apiSchema,
  mt: mtSchema
}

new ApiManager({ schema: schema57 })
```

**Comment by FragsterAt** [comment]
How I can use https://core.telegram.org/schema/json ? Shemas from  https://github.com/zerobias/telegram-mtproto/tree/mtproto2/schema contain errors (3rd api method, that i probe: getDialogs :))

**Comment by goodmind** [comment]
@FragsterAt scheme from telegram site is outdated

**Comment by FragsterAt** [comment]
@goodmind ok, but where can I get the actual API documentation?

**Comment by goodmind** [comment]
@FragsterAt nowhere :)

**Comment by DenisIzmaylov** [comment]
It would be great. Let's keep this issue for tracking this change requests to the docs.

**Comment by stek29** [comment]
@FragsterAt there's no publicly available API documentation.
However, I find tjhorner.com/tl-schema and tjhorner.com/webogram really useful when playing around with API.

Also, schema at Telegram site doesn't have mtSchema in it afaiu.

**Comment by zerobias** [comment]
@stek29 Wow, great! I found only 57 json schema

**Comment by zerobias** [comment]
Looks like we should implement Type Language schema translator

**Comment by stek29** [comment]
@zerobias I have made a simple script, but it's written in Python 🙃

**Comment by zerobias** [comment]
@stek29 It would be great) Python isn't a problem

**Comment by stek29** [comment]
@zerobias sorry, I've lost link to this repo, lol.
I've made a [gist](https://gist.github.com/stek29/067ce1d4d764147e21cc0667ba5c063d) for now.
I want to add support for other formats (like Android's app TLRPC.java) later, I'll make a repo when I do it.

**Comment by zerobias** [comment]
@stek29 thanks!

**Comment by wfjsw** [comment]
You could get latest schema [here](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl) and my little parser in js [here](https://gist.github.com/wfjsw/edabe83e3057fbb50c72ca1e5de1d3a5) :)

**Comment by wfjsw** [comment]
However, actually I am wondering how can you tell the difference between apiSchema and mtSchema?

**Comment by zerobias** [comment]
@wfjsw Is something wrong? I see that there are no flags in the scheme, but otherwise, everything seems to be fine

**Comment by wfjsw** [comment]
@zerobias Since I have nothing to validate the generated schema file, the only proofreading tool I have is my eyes.
Fixed Bugs:
Revision 2 - fix 'method' being parsed as 'predicate'
Revision 3 - fix param `{X:Type}` being parsed as `{X` `Type}`
Revision 4 - fix compacter that fails to remove all `;`
Revision 5 - make `vector` have no params

I believe there is more bugs that I haven't discovered.

**Comment by zerobias** [comment]
@wfjsw In addition to the main application scheme, there is a scheme for the low, network layer. It is described [here](https://core.telegram.org/schema/mtproto).

At the moment I am working on an application to view the schemes and navigate them conveniently. I tried to include this code there, and the scheme was interpreted correctly, I did not notice any issues

**Comment by wfjsw** [comment]
@zerobias I was hit by exceptions when I am working with old telegram.link code with l62.

Have to work with obsolete code coz I got confusing `AUTH_KEY_EMPTY` when I call `auth.importBotAuthorization`.

**Comment by zerobias** [comment]
@wfjsw Can you open the issue and describe the problem in more detail? Ideally, if there will be a code example to reproduce the problem step-by-step

**Comment by wfjsw** [comment]
@zerobias I will do it soon.
Meanwhile I have updated tl_convert so it parse signed decimel correctly.
And, it seems mtproto schema should never be updated. The L62 schema file occupied from tdesktop is changing every `bytes` into `string` in that section.

**Comment by goodmind** [comment]
This should be done with https://github.com/zerobias/ties and schema fetcher from tdesktop repo

**Comment by ZAYEC77** [comment]
Hello guys

I try to update the schema.
I want to use this file https://tjhorner.com/tl-schema/schema.json as `schema`.
What should I pass as `mtSchema`?

Thanks

**Comment by goodmind** [comment]
@terrasoff NEVER believe to official docs

**Comment by goodmind** [comment]
https://github.com/zerobias/telegram-mtproto/issues/159
