### ISSUE TITLE
How to upload profile photo for my account

### ISSUE THREAD

**Issue by Alavi1412** [zerobias/telegram-mtproto#100]
I want to add profile photo to my account but I don't know how. Can I upload it using an external link?

**Comment by Alavi1412** [comment]
NO ANSWER?

**Comment by goodmind** [comment]
no answer

**Comment by IlyaKronos** [comment]
@goodmind You are collaborator of this package and you can't give answer to this question? Is this so hard?

**Comment by 2012mjm** [comment]
Open the web version of the telegram and view the logs in the browser debugger.
You can see which methods have been used

Api call account.updateStatus
**Api call upload.saveFilePart** [https://tjhorner.com/tl-schema/method/upload.saveFilePart](url)
Api call upload.saveFilePart
Api call upload.saveFilePart
Progress 0.35993760847118783
Api call account.updateStatus
Progress 0.7198752169423757
**Api call photos.uploadProfilePhoto** [https://tjhorner.com/tl-schema/method/photos.uploadProfilePhoto](url)
Rpc response photos.photo
**Api call upload.getFile** [https://tjhorner.com/tl-schema/method/upload.getFile](url)
Rpc response upload.file
