### ISSUE TITLE
undefined error

### ISSUE THREAD

**Issue by Alavi1412** [zerobias/telegram-mtproto#101]
I use this code
```
const  test  = await client('messages.getAllChats', {
        except_ids: [8]
    });

    console.log(test);
```
but I get following error:
Error undefined undefined 2 5

**Comment by zerobias** [comment]
Do you try it on `3.2.11`?

**Comment by Alavi1412** [comment]
"telegram-mtproto": "^3.0.5-unstable"
this is my version.

**Comment by Alavi1412** [comment]
when I upgrade to 3.2.11 my code completely stop working and just wait at first request to telegram

**Comment by goodmind** [comment]
This looks like DC related issue
