### ISSUE TITLE
Endless promises

### ISSUE THREAD

**Issue by Alavi1412** [zerobias/telegram-mtproto#103]
when I use a method and I do something wrong(or internet go disconnected), my code completely stop working and wait forever because the source code of the methods doesn't handle the promises at error and this cause some kind of crash in my app.
and I can't handle the error in my code,
for example when I enter the wrong phone number, it said INVALID_PHONE_NUMBER and my app wait forever because the method didn't return promise,
please handle that

**Comment by goodmind** [comment]
@Alavi1412 but it returns promises

**Comment by Alavi1412** [comment]
@goodmind So why it wait forever?

**Comment by zerobias** [comment]
@Alavi1412 
> because the method didn't return promise
Interesting, which version do you use?

**Comment by Alavi1412** [comment]
I have tested all versions, I can't handle the errors in my codes, latest version I have testes I think was 3.2.11

**Comment by wfjsw** [comment]
In my case the error is caught but it retry the failed request itself in a infinite loop.

**Comment by agogex** [comment]
I think this is the same #111 problem. Can't get an error in the catch section,  for any way, promise or async/await. Please help to resolve this issue.

**Comment by febrihardians** [comment]
i can not caught error too and in the console i have warning "a promise was rejected with a non-error"

**Comment by kesor** [comment]
The exceptions `AUTH_KEY_UNREGISTERED` and `AUTH_RESTART` are silently removed and not thrown. I assume that `single-handler.js` is trying to load the auth keys from storage. But it should really throw the error if it doesn't work since it might be that the user has never signed-in yet and no auth id exists.

**Comment by ali-mahmoodvand** [comment]
Me too cant catch errors , i set debug boolean to true in app config , but not working 
help us 
```const app = {
  debug:true,
    storage: new Storage('./storage.json')
}```
@zerobias @wfjsw

**Comment by Baael** [comment]
Debug isn't working for me either. However everytime it hangs silently in await, I have to remove `storage.json` and sign in again. 
@alpha

**Comment by callmez** [comment]
same problem to me , any news for this?

**Comment by nagashik** [comment]
looks like the same truble for me #171

**Comment by nagashik** [comment]
did someone solve this problem?

**Comment by amarcus** [comment]
Relax guys this project is dead, face it. Latest stable version is 3.2.7 use it. Zerobias doesn't give a shit about his project is totally not working. No docs, no wiki, garbage code, not working examples, a freaking mess.
