### ISSUE TITLE
package print AUTH repeatly with not action

### ISSUE THREAD

**Issue by Alavi1412** [zerobias/telegram-mtproto#104]
When I use storage sometimes my app just print AUTH many times and never start working.
I'm worried about that what if I lose my users login authentication. If I lose them, I lose a lot of money.

please answer fast , Did I losed them or it is just a bug of package and can be solved?

**Comment by goodmind** [comment]
@Alavi1412 why you use alpha version in production?

**Comment by Alavi1412** [comment]
so what is the last version?
I use @latest to install the package but It says AUTH_KEY_UNREGISTERED
