### ISSUE TITLE
TypeError: MTProto is not a function

### ISSUE THREAD

**Issue by dundas** [zerobias/telegram-mtproto#105]
I'm using the sample code to get started, but I'm getting this error: 
const client = MTProto({webogram: true, dev: true})
               ^
TypeError: MTProto is not a function
    at Object.<anonymous>

Anyone else see this getting started, or can point me in the right direction to figuring it out? 

Here's my code below: 

`const MTProto = require('telegram-mtproto')
const phone = {
  num : '+9996620001',
  code: '22222'
}

const api = {
  layer          : 57,
  initConnection : 0x69796de9,
  api_id         : 49631
}

const server = {
  dev: true //We will connect to the test server.
}           //Any empty configurations fields can just not be specified

const client = new MTProto({ server, api })

async function connect(){
  const { phone_code_hash } = await client('auth.sendCode', {
    phone_number  : phone.num,
    current_number: false,
    api_id        : 49631,
    api_hash      : 'fb050b8f6771e15bfda5df2409931569'
  })
  const { user } = await client('auth.signIn', {
    phone_number   : phone.num,
    phone_code_hash: phone_code_hash,
    phone_code     : phone.code
  })

  console.log('signed as ', user)
}

connect()
`

**Comment by Alavi1412** [comment]
You are using old version.
change your package.json content about telegram-mtproto to this:
"telegram-mtproto" : "^2.2.2"
and Also version 3.0.11 I think is good

**Comment by dundas** [comment]
Thanks! I think I had that in my package.json, but I'll try to update and see if that works!

**Comment by dundas** [comment]
No luck. Made the update still same error. 

![screen shot 2017-10-09 at 1 20 04 pm](https://user-images.githubusercontent.com/627426/31352729-dddb1368-acfd-11e7-931e-fbfc3a051346.png)

**Comment by OwnageIsMagic** [comment]
Start interactive node shell and try to inspect package

**Comment by dundas** [comment]
Will do...what am I inspecting for?

**Comment by OwnageIsMagic** [comment]
Error says that MTProto is not a function but an Object, so I suggest you to inspect it
Maybe after that you will be able to resolve this issue by yourself

**Comment by dundas** [comment]
Sure thing. I can definitely dig a bit deeper, I was just wondering whether everyone who uses this API has to fix the same problem. In that case I can report its as a bug. 

But I'll dig a bit deeper to find a fix, and report back what I come up with.

Cheers.

**Comment by OwnageIsMagic** [comment]
The main problem that author named version `3.x.x` instead of `0.3.x.x`
This lib in pure alpha state but there is no info about it
Regardless your problem I think you should use 
`const {MTProto} = require('telegram-mtproto')` , because this package now return not just its constructor, but a collection of functions
You can look for more up to date examples here https://github.com/zerobias/telegram-mtproto/issues/59#issuecomment-306504287 or in other issuses

**Comment by zerobias** [comment]
@OwnageIsMagic no, library never exported the main function directly, even 1.x branch already has exports like this

@dundas You used commonjs import (require), which *always* works differently than es6 imports, so your option never worked
`const { MTProto } = require('telegram-mtproto')`

**Comment by dundas** [comment]
That worked like a charm. Thanks @zerobias!

**Comment by christoph-puppe** [comment]
@OwnagelsMagic that ).MTProto in the require helped, now it loads! yay!

**Comment by christoph-puppe** [comment]
Thanks @OwnageIsMagic ! that ).MTProto in the require helped, now it loads 👯‍♂️

**Comment by dawadam** [comment]
Why documentation is not update ?

    const MTProto = require('telegram-mtproto')

MTProto is not a function
