### ISSUE TITLE
Infinite retry on failed request

### ISSUE THREAD

**Issue by wfjsw** [zerobias/telegram-mtproto#113]
In short,
I was using `contacts.resolveUsername` to figure out an username. If the request succeed, nothing special happened. But when an error was thrown(for example, unoccupied username), the library is constantly reissue the request(very quick).

**Comment by dvkndn** [comment]
In our case clearing the storage does help. I guess there's something wrong with expiration of the data in storage?

We also implemented a hack to avoid this: in the beginning, we will fire one public request and have a 5s time out for it:

- If in 5s we got the data, that means the request was successful, no loop issue, we then move on with the rest of the app
- If after 5s we still hadn't got the data, that means it seems we are in a loop, so we clear the storage and start again (simply page reload if lazy)

**Comment by wfjsw** [comment]
5 seconds is enough to get FLOOD_WAIT I think :/
And clearing the storage means I have to reauthenticate.
