### ISSUE TITLE
How to implant mtproto

### ISSUE THREAD

**Issue by Darklight256** [zerobias/telegram-mtproto#119]
I want to implement the mtproto by myself with nodejs but I don't know where should I start. I try to read your package but I didn't understand it and I try to read the protocol of telegram and I confused.
How can I create a connection with telegram server and transfer data with it?
Where should I start from to develop such a package like yours?

**Comment by Alavi1412** [comment]
It was my question too @goodmind ,
I try to connect to telegram server but I got nothing. How do you create mtproto?

**Comment by goodmind** [comment]
Why do you want your own package?

**Comment by Alavi1412** [comment]
Because I want to create some packages like this in other languages and I want to contribute to your package too and modify and inmprove it.

**Comment by dundas** [comment]
Do you want to work together to learn how to use the package? I have been having a hard time figuring it out myself.

**Comment by Alavi1412** [comment]
We are looking for a starting point, Where should we start connecting to telegram server?
@dundas

**Comment by dundas** [comment]
@Alavi1412 Would you want to join a slack chat and work together to get it working?

**Comment by Alavi1412** [comment]
@dundas , Yes Of course

**Comment by aticus7886** [comment]
@dundas , would love to join a slack and work together to get it working.
I have difficulties with an invalid_code error when trying to sign in.

**Comment by Roy5000** [comment]
@aticus7886 is the slack channel still active?  If possible I would like to join, I try to implement MT Proto as well and running in similar difficulties.

**Comment by jabsatz** [comment]
@Alavi1412 @dundas @aticus7886 did you guys manage anything? I'm having a hard time with this as well
