### ISSUE TITLE
auth.sendSms support

### ISSUE THREAD

**Issue by PsiXdev** [zerobias/telegram-mtproto#120]
Hello, will the library support such api method as auth.sendSms? Are there any problems?

**Comment by tulir** [comment]
You can call any API methods at least on the latest 3.x.x versions, so `auth.sendSms` should work just fine.

**Comment by tulir** [comment]
Did you read the [examples](https://github.com/zerobias/telegram-mtproto/tree/feature/mtproto3/examples) and [FAQ](https://github.com/zerobias/telegram-mtproto/wiki/FAQ)? The object returned when creating an MTProto instance returns a function that you call to call Telegram API methods.
```js
const MTProto = require("telegram-mtproto")
...
const client = MTProto(configObject)
...
const response = await client("auth.sendSms", argsObject)
```

**Comment by PsiXdev** [comment]
Yes, I do everything just like that.

**Comment by tulir** [comment]
`auth.sendSms` may be removed from the Telegram side. https://core.telegram.org shows it, but that site is horribly outdated (at layer ~24 while latest is 71). You can view the latest schema at https://tjhorner.com/tl-schema/

**Comment by goodmind** [comment]
@tulir thanks

**Comment by PsiXdev** [comment]
Interesting. And why does the library not work with 71 layers? A large number of errors appear on queries:
```
[30.168] parse error Constructor not found: 213142300 9473 1319329675 Error: Constructor not found: 213142300 9473 1319329675
    at Deserialization.fetchObject (/<...>/node_modules/telegram-mtproto/lib/tl/index.js:488:15)
```
I'm doing something wrong? With layer 57 everything works fine.

**Comment by OwnageIsMagic** [comment]
Because it only knows about layer 57
https://github.com/zerobias/telegram-mtproto/tree/master/schema

**Comment by PsiXdev** [comment]
This is problem. Ok, thanks

**Comment by goodmind** [comment]
@PsiXdev this is not problem. You can pass your own layer json file
