### ISSUE TITLE
Graceful disconnection

### ISSUE THREAD

**Issue by unger1984** [zerobias/telegram-mtproto#122]
How to disconnect from the server? I have not found it anywhere in the examples. What was previously in Telegram.client.done ()

**Comment by unger1984** [comment]
Изучив большую часть кода, понял что в системе слишком много таймеров. Добавить обработчик состояния в каждый очень сложно. Я решил использовать такой хак:

```
// Black Magic !!!
        let list = process._getActiveHandles();
        for(let i=0; i<list.length; i++){
            let handle = list[i];
            if (Object.prototype.toString.call(handle) === '[object Timer]') {
                if(handle._list.msecs%10 ==0) {
                    handle.unref();
                }
            }
        }
```

А в своей системе буду ипользовать в таймерах значение не делящееся 10

**Comment by goodmind** [comment]
lol, why would you want to disconnect?

**Comment by unger1984** [comment]
My program should go into telegrams under the account, perform some actions, go out, and transfer control further. And without breaking the connection it hangs.

**Comment by OwnageIsMagic** [comment]
If you know that all information you want already received, you can call `process.exit(0)`

**Comment by unger1984** [comment]
No, the program should not be terminated at the same time

**Comment by tsarpaul** [comment]
I'm facing this issue as well. Would be nice to have a way to stop the client gracefully.
