### ISSUE TITLE
[9.401] Error 400 PHONE_CODE_EXPIRED 2 1

### ISSUE THREAD

**Issue by dundas** [zerobias/telegram-mtproto#124]
I have broken the login down into two steps: 

STEP 1: Get code and hash 

```
const {MTProto} = require('telegram-mtproto');
const {Storage} = require('mtproto-storage-fs')



const phone = '+19179999999'
const api = {
  layer: 57,
  initConnection: 0x69796de9,
  api_id: XXXXX,
  app_version: '1.0.1',
  lang_code: 'en'
}
const server = {webogram: true,dev: false}
const client = MTProto({api,server})

    let sendPhoneCode = client('auth.sendCode', {
      phone_number: phone,
      current_number: true,
      api_id: XXXXX,
      api_hash: XXXXXXXXXXXXX'
    })

    sendPhoneCode.then(codeResponse => {
      console.log(codeResponse)
    })

```

From that I receive the code on my phone and the codeResponse prints this code: 

```
{ _: 'auth.sentCode',
  flags: 3,
  phone_registered: true,
  type: { _: 'auth.sentCodeTypeApp', length: 5 },
  phone_code_hash: 'f8a1ee55f04d8ae7a4',
  next_type: { _: 'auth.codeTypeSms' } }
```
STEP 2: 
I then take the hash and the code and put it in this script:

```
const { MTProto } = require('telegram-mtproto');
const { Storage } = require('mtproto-storage-fs');

const app = { storage: new Storage('./storage.json') }


const phone = {
  num : '+19179999999',
  code: '12345', 
  phone_hash : 'XXXXXXXXXXXXXX'
}
const api = {
  layer          : 57,
  initConnection : 0x69796de9,
  api_id         : XXXX
}

const server = { webogram: true, dev: false }


const client  = MTProto({ server, api })

//function login(client, phone){

let signIn = client('auth.signIn', {
  phone_number   : phone.num,
  phone_code_hash : phone.phone_hash ,
  phone_code     : phone.code
})

signIn.then(signInResult=>{
  console.log(signInResult)
})
```

And the error I receive is:

[9.401] Error 400 PHONE_CODE_EXPIRED 2 1
Unhandled rejection (<{"code":400,"type":"PHONE_CODE_EXPIRED...>, no stack trace)

Even if I enter within a minute I keep on getting this error. Can anyone help me get this working?

**Comment by unger1984** [comment]
`auth.sendCode` and `auth.signIn` must be in the same object MTProto. Without disconnection

**Comment by dundas** [comment]
@unger1984 Thank you! In this case how is it possible receive the code to the phone and enter it back into the auth.signIn in the same object?

**Comment by dundas** [comment]
@unger1984  OK I've switched up my approached based on your tip. Here's my new code: 

Step 1: Still send code to phone 

```
const {MTProto} = require('telegram-mtproto');
const {Storage} = require('mtproto-storage-fs')
const phone = '+19179999999'
const api = {
  layer: 57,
  initConnection: 0x69796de9,
  api_id: XXXXX,
  app_version: '1.0.1',
  lang_code: 'en'
}

const server = {
  webogram: true,
  dev: false
}

const client = MTProto({
      api,
      server
    })

    let sendPhoneCode = client('auth.sendCode', {
      phone_number: phone,
      current_number: true,
      api_id: xxxxx,
      api_hash: 'xxxxxxxxxxxxxxxxxxxx'
    })

    sendPhoneCode.then(codeResponse => {
      console.log(codeResponse)
    })
```

Step 2: Enter code, in phone object, but run full login from there: 

```
const {
    MTProto
} = require('telegram-mtproto');
const {
    Storage
} = require('mtproto-storage-fs');

const app = {
    storage: new Storage('./storage.json')
}

const phone = {
    num: '+19179999999',
    code: '11092'
}
const api = {
    layer: 57,
    initConnection: 0x69796de9,
    api_id: xxxxxx
}

/*const server = {
  dev: true
}*/
const server = { webogram: true, dev: false}

const client = MTProto({
    server,
    api
})


let  getPhoneHash =  client('auth.sendCode', {
        phone_number: phone.num,
        current_number: false,
        api_id: xxxxxx,
        api_hash: 'xxxxxxxxxxxxxxx'
    })

let signIn = getPhoneHash.then(codeResponse=>{
  
    return client('auth.signIn', {
        phone_number: phone.num,
        phone_code_hash: codeResponse.phone_code_hash,
        phone_code: phone.code
    })

})

signIn.then(result=>{
    console.log(result)
})

```

The error I get now is this: 

[6.995] Error 400 PHONE_CODE_INVALID 2 1
Unhandled rejection (<{"code":400,"type":"PHONE_CODE_INVALID...>, no stack trace)

I'm very confused about how you send the code to your phone, but enter it in the same object for sign in. 

Thanks again for any help. Cheers!

**Comment by unger1984** [comment]
For testing, I, for example, use this:

```javascript
const read = (msg) => {
    return new Promise((resolve, reject) => {
        console.log(msg)
        let input = ''
        process.stdin.resume()
        process.stdin.setEncoding('utf8');
        process.stdin.on('data', data => {
            input += data;

            if (data.indexOf('\n') != -1) {
                input = input.replace('\n', '');
                process.stdin.pause();
                resolve(input);
            }
        });
    });
}

const testReal = async (phone) => {
    try {
        let phone_hash = await tg.sendCode(phone)
        let sms = await read("SMS Code?")
        let auth = null;
        if (await tg.checkPhone(phone)) {
            tg.pause(1)
            auth = await tg.signIn(phone, phone_hash, sms)
        } else {
            tg.pause(1)
            auth = await tg.signUp(phone, phone_hash, sms, "TestName", "TestSecond")
        }
        let user_id = auth.user.id;
        console.log("user", user_id);
        tg.setUserAuth(2, {id: user_id});
        tg.pause(1)
        tg.done()
    } catch (e) {
        console.dir(e);
        tg.done()
    }
}
```

tg - his is the wrapper class over MTProto. read - read sms code from stdin

**Comment by unger1984** [comment]
I`m use SimpleFileStorage for save auth data between sessions

**Comment by dundas** [comment]
@unger1984 I see thanks. I have to figure out how to keep MTProto open (or pass the object) when I receive the code.

**Comment by Roy5000** [comment]
@dundas  did you figured out how to keep MTProto open when receiving the code?  I have similar issues with phone code verification.  (topic: https://github.com/zerobias/telegram-mtproto/issues/88) and think your solution can maybe help

**Comment by Roy5000** [comment]
Found a workaround to keep MTProto open when SMS code is received.  I saved the SMS code in an external JSON file and added a delay of 30 seconds between SendCode and SignUp.  This gave me 30sec to update the JSON file with SMS code.

config.json:
`{
    "sms" : "7****7"
}`

js code:

`const delay = require('delay');

let MTProto = require('telegram-mtproto').MTProto

const phone = {
  num : '+3**********5',
  code_hash: 'b*************d'
}


const api = {
  layer          : 57,
  initConnection : 0x69796de9,
  api_id         : 1*****1
}

const server = {
  dev: true //We will connect to the test server.
}           //Any empty configurations fields can just not be specified

const client = MTProto({ server, api })

async function connect(){   

   
  const { phone_code_hash } = await client('auth.sendCode', {
    phone_number  : phone.num,
    current_number: false,
    api_id        : 1*****1,
    api_hash      : 'c***************************3'
  })
  

  await delay(30000);

    
  var config = require('./config.json');
    
  const { user } = await client('auth.signUp', {
    phone_number   : phone.num,
    phone_code_hash: phone_code_hash,
    phone_code     : config.sms,
    first_name      : 'YourName'
  })
  

  console.log('signed as ', user)
}

connect()

`

**Comment by OwnageIsMagic** [comment]
@Roy5000 To insert code block in markdown use triple backtick (` ``` `) 
````
```
Code
```
````
To enter sms code you can use keyboard (see https://github.com/zerobias/telegram-mtproto/issues/124#issuecomment-347812568 `read` function)

**Comment by Roy5000** [comment]
Thanks @OwnageIsMagic .

The first Sign Up went successful and I received below response.  After restart I tried to run script again but Telegram does not sent SMS codes anymore.  Is this because I'm still signed up/in with phone number?

I assume the the signup with SMS code is only onetime needed and from then need to use the ID / AccessHash from response?   

Looking for function / method how to SignIn after the first time.

```
{ _: 'user',
  flags: 1043,
  self: true,
  id: 5****,
  access_hash: '1*****************0',
  first_name: 'Roy',
  phone: '3*****5' }
```

**Comment by OwnageIsMagic** [comment]
https://translate.google.ru/#en/auto/signIn%20signUp

**Comment by Roy5000** [comment]
Thanks, I think I got the difference between SignIn and SignUp. The first time you need to SignUp to register, parameters for this function are phonenumber,  phone hash code, sms code and first name.
The next time you need to SignIn instead of SignUp. Parameters for this function are phonenumber,  phone hash code, sms code.

The SignUp went succesfull but when I run function sendcode again (to get phone hash) I don't receive a sms code. And if i understand the function correct this sms code is alsof needed for SignIn.  What could be wrong? (Could it be a limit of max. Sms messages received?)

**Comment by OwnageIsMagic** [comment]
You need registration(sign up) only once per phone number
After that log in(sigin in) into account using
```js
async function login(client, phone){
  const { phone_code_hash } = await client('auth.sendCode', {
    phone_number  : phone.number,
    current_number: false,
    api_id        : 001,
    api_hash      : 'fb569'
  })
  const sigin = await client('auth.signIn', {
    phone_number   : phone.num,
    phone_code_hash: phone_code_hash,
    phone_code     : sms.code // <-- enter sms code here
  })

  console.log('sigin user info', sigin);
}
```

**Comment by Roy5000** [comment]
My issue with not receiving telegram SMS code is solved after I moved to version  3.2.11.

**Comment by onezens** [comment]
I solve this issue, here is my code
```

const readline = require('readline');
const { MTProto } = require('telegram-mtproto');

const  rl = readline.createInterface({
    input:process.stdin,
    output:process.stdout
});



const phone = {
    num : '+8613157064993'
};

const info = {
    first_name: 'xiaoming1',
    last_name: 'wang'
};



const app = {
    api_id: 115826,
    api_hash: 'aa866cf94d15ad9a9f9d69a399b1e588'
}


const api = {
    layer         : 58,
    initConnection: 0x69796de9,
    api_id        : app.api_id
};

const server = {
    dev: true //We will connect to the test server.
};        //Any empty configurations fields can just not be specified

const client = MTProto({ server, api });


async function checkPhone(){
    console.log('start to checkPhone');
    const result = await client('auth.checkPhone', {
        phone_number: phone.num
    });
    console.log('checkPhone result: ' + JSON.stringify(result));
    return result.phone_registered;
}

async function inputWait(inputDesc, next){
    rl.question(inputDesc,function(rel){

        next(rel.replace('\n', ''));
        rl.close();
    });
}

// console.log(inputWait('input'));

async  function startSignUp(code,phone_code_hash) {
    console.log('start to signUp, code: %s phone_code_hash: %s', code, phone_code_hash);
    const result = await client('auth.signUp', {
        phone_number: phone.num,
        phone_code_hash: phone_code_hash,
        phone_code: code,
        first_name: info.first_name,
        last_name: info.last_name
    });
    console.log('sign up completed, result: ' + JSON.stringify(result));

    await signIn()
}

async function signUp() {

    const phone_code_hash = await sendCode();


    await inputWait('input phone num: ', function (code) {
        startSignUp(code, phone_code_hash);
    });

}

async function sendCode(){
    console.log('await send code.');
    const result = await client('auth.sendCode', {
        phone_number  : phone.num,
        current_number: true,
        api_id        : app.api_id,
        api_hash      : app.api_hash
    });
    
    console.log('send code completed , result: ' + JSON.stringify(result));
    return result.phone_code_hash;
}
async function startSignIn(code, phone_code_hash) {
    console.log('start to signIn with number code: %s phone_code_hash: %s phone: %s' ,code, phone_code_hash, phone.num);
    const { user } = await client('auth.signIn', {
        phone_number: phone.num,
        phone_code_hash: phone_code_hash,
        phone_code  : code
    });
    console.log('signed as ', user)
}
async function signIn(){

    const phone_code_hash = await sendCode();

    await inputWait('phone num code: ', function(code){
        startSignIn(code, phone_code_hash);
    });

}

async function logOut() {
    console.log('start to logout');
    const result = await client('auth.logOut');
    console.log('logout completed, result: ' + JSON.stringify(result));
}

async function connect(){
    await signUp();
    if(await checkPhone()){
        // await logOut();
        //sign in
        await signIn();

    }else{
        //sign up
        await signUp();

        //sign in
        // await signIn();

    }

}



connect();
```

**Comment by hlalibe** [comment]
Hi guys,

I already have an account setup on Telegram. I want to use this code to read my incoming messages. I used the code on the front page and plugged in my phone number, api, hash,...but when i run the code below i get the Phone_Code_expired error message. I receive 5 digits code by SMS but it's not clear to me how i can sign in. I've tried the code above from Onezens but i get the same error (and it seems this code is to signup , i just want to sign in).

`
```
//var MTProto = require("MTProto")
const { MTProto } = require('telegram-mtproto')

//import MTProto from 'telegram-mtproto'

const phone = {
  num : '+41xxxxxxx',
  code: '12345'
}

const api = {
  layer          : 57,
  initConnection : 0x69796de9,
  api_id         : 123456
}

const server = {
  dev: true //We will connect to the test server.
}           //Any empty configurations fields can just not be specified

const client = MTProto({ server, api })

async function connect(){
  const { phone_code_hash } = await client('auth.sendCode', {
    phone_number  : phone.num,
    current_number: false,
    api_id        : 123456, // obtain your api_id from telegram
    api_hash      : '6rt765rf65rfdzertu8975rff' // obtain api_hash from telegram
  })
about:blank
```
`

**Comment by OwnageIsMagic** [comment]
you need to register on test server to use it
```js
const server = {
  dev: true //We will connect to the test server.
}
```
Look at [this example](https://github.com/zerobias/telegram-mtproto/blob/30eff2e3b7511315d4e3383186302a91baf430c1/examples/node-storage.js) on how to enter sms code

**Comment by hlalibe** [comment]
i see.
But i don't want to use the test server if i want to get my messages , no ?

Following your example link, i see that node-storage.js uses dev: false. so that's prod server, right ?

I have updated my phone number, api ,....then i run node-storage.js and now i receive ->
not signed in
[1.343] Error 401 AUTH_KEY_EMPTY 2 1
[1.742] Error 401 AUTH_KEY_UNREGISTERED 2 1
and nothing else happens. 

i tried to run login.js first but then i receive->
Error: Cannot find module '../lib'

??

**Comment by adavidof** [comment]
@unger1984 
thanks!
finally I did it.
