### ISSUE TITLE
Error: CHANNEL_INVALID

### ISSUE THREAD

**Issue by iam-medvedev** [zerobias/telegram-mtproto#126]
Hi! I'm trying to join channel, but have no success.
I tried different variations of the channel_id, for example: 1001188085, -1001188085, 1188085, -1188085.

Maybe i using wrong access_hash? Here is hash, returned from auth.signIn method.

```
const channel = await client('channels.joinChannel', {
        channel: {
            _: "inputChannel",
            channel_id: -1001001188085,
            access_hash: 76**************92
        }
    });
    console.log(channel);
```
returns me:
`Error: CHANNEL_INVALID`

**Comment by OwnageIsMagic** [comment]
Maybe you connecting to testnet ( `{dev: true }` )?

**Comment by iam-medvedev** [comment]
@OwnageIsMagic No, here is my config:

```
const api = {
	invokeWithLayer: 0xda9b0d0d,
	layer          : 57,
	initConnection : 0x69796de9,
	api_id         : config.TELEGRAM.ID,
	app_version    : '1.0.1',
	lang_code      : 'en'
}

const server = {
	webogram: true,
	dev: false
};
```

**Comment by OwnageIsMagic** [comment]
I think something wrong with your channel id
Its bigger than 4kkk  (32bit int max value)

**Comment by dew01ke** [comment]
what about contacts.resolveUsername? you can try this method to obtain correct access_hash

**Comment by iam-medvedev** [comment]
@dew01ke exactly, my access_hash was wrong.
