### ISSUE TITLE
The connection hangs

### ISSUE THREAD

**Issue by unger1984** [zerobias/telegram-mtproto#127]
Hi!

I'm using JsonStrorage from the examples in which I store the authorization data. When i try to use a saved copy in a new connection, everything works fine. 

But if several hours have passed, the call of the api methods hangs. Any api methods. And that do not require authorization. For example, help.getConfig. The application simply hangs on `await client("help.getConfig")`

Maybe there should be throw some error in this case? But nothing like this happens.

I'm using telegram-mtproto ver 3.2.11

**Comment by iam-medvedev** [comment]
Try `telegram-mtproto@3.2.7`
You can turn logs on, there is a lot of debug info. `DEBUG=* node app.js`

**Comment by unger1984** [comment]
Thanks! telegram-mtproto@3.2.7 worked!

**Comment by unger1984** [comment]
How checkout code telegram-mtproto@3.2.7 ?

**Comment by iam-medvedev** [comment]
@unger1984 npm install telegram-mtproto@3.2.7

**Comment by unger1984** [comment]
I wanth git roolback to telegram-mtproto@3.2.7

**Comment by iam-medvedev** [comment]
Source is [here](https://github.com/zerobias/telegram-mtproto/tree/083d8c4cd096502e9c347eb1f4a4191ca939842a/packages/telegram-mtproto). #

**Comment by unger1984** [comment]
@iam-medvedev thanks!
