### ISSUE TITLE
Errors are leaking

### ISSUE THREAD

**Issue by moltar** [zerobias/telegram-mtproto#128]
It seems like the errors are leaking here. Then there is also the console pollution.

https://github.com/zerobias/telegram-mtproto/blob/1006de5c91b7cde22ba859a65a5623a9edc44103/src/service/api-manager/index.js#L237

Basically, when I'm un-authed, and trying to make a request to a resource, I just get the following output on the screen:

```
[1.017] Error 401 AUTH_KEY_UNREGISTERED 2 1
[1.375] Error 401 AUTH_KEY_UNREGISTERED 2 1
```

Then the console hangs and never resolves or rejects.

**Comment by flavianohonorato** [comment]
I have this same problem, I get the following error when I use the `sendInvites()` endpoint:
<img width="660" alt="screen shot 2018-01-30 at 08 07 59" src="https://user-images.githubusercontent.com/4780299/35563195-bc68d4a0-0594-11e8-8b88-cb48771508ee.png">
