### ISSUE TITLE
MTPROTO Alternatives 

### ISSUE THREAD

**Issue by dundas** [zerobias/telegram-mtproto#132]
For anyone reading this, and having trouble with this library. I this it's a great start however for nodejs I spent days trying to make this work and I couldn't. You can see some of my challenges [here](https://github.com/zerobias/telegram-mtproto/issues/117), [here](https://github.com/zerobias/telegram-mtproto/issues/124) and [here ](https://github.com/zerobias/telegram-mtproto/issues/125). Admittedly some of my issues stemmed from the fact that I am still learning es6. However there's not a ton in the way of documentation or working examples to help you along if you want to use this library. 

A couple of things to note that I really struggled with: 
1. You need to be sure that the code is generated, and entered in the same script as its entered. So you somehow need to either have an SMS API, or a form with session saved to enter the code.  Once I generated the code. I paused the script entered the code in a runkit notebook here: https://runkit.com/dundas/tgcode which as then called 60 seconds later to complete running my code.

2. There are odd errors for example I continued to receive the following error even though I'm 100% positive that my settings were correct: 

```
[9.203] Error 400 API_ID_INVALID 2 1
{ code: 400,
  type: 'API_ID_INVALID',
  description: 'CODE#400 API_ID_INVALID',
  originalError: 
   { _: 'rpc_error',
     error_code: 400,
     error_message: 'API_ID_INVALID' } } 

```

3. After a few tests, telegram stopped sending SMS to my phone. However if you are logged into the app already you can get the code in the APP. That is UNLESS you are in dev mode by setting: 
```

const server = {
    dev: true
}

```
This will continue to send the message to your phone, however once I set dev mode, then I faced other errors. 

All in all I'd recommend a project more stable for production use.  I ended up coming across the Telethon Library in Python: https://github.com/LonamiWebs/Telethon that I was able to use. 

Once I re-acquainted with Python, it took me all of 2 days to write the code that I needed, there were no mysterious errors, and the documentation is some of the best I've seen for most projects. 

Because my Python coding experience is limited as is my usecase, I just created a basic REST api around my Python script to handle the basic sending and receiving functionality. 

To  be fair, the Telegram API is one of the most complicated and convoluted I've ever come across, and support seems to be fairly abandoned as they focus on their bot platform, so I don't fault this project, and I think the people working on it are working hard to deliver something that works. However, there are alternatives out there, if you're struggling like I was. 

Hope this helps anyone else trying to get started. 

Cheers.

**Comment by OwnageIsMagic** [comment]
Добавь уже в ридми что проект в данный момент не в лучшем состоянии
Надоели эти ноющие арабы и индусы которые  полгода лёрнинг ес 6 всё никак не могут

**Comment by danog** [comment]
Or add a RTFM section

**Comment by zerobias** [comment]
I plan to do major update for the project from next year, make it easier and more understandable

**Comment by stek29** [comment]
RTFM please. You don't know shot about Telegram APIs or JS and you're complaining this lib is bad

3. You'll be on completely different server when dev mode is enabled, with completely different account. You can switch to dev server in TDesktop (by typing testmode in settings), in Android beta (switch DC in settings), iOS beta (which is private, but you can use one of Iranian forks or if you have jailbreak -- use my Telenhancer tweak) and Webogram (I don't remember, have a look into config.js).

**Comment by stek29** [comment]
I like how issue title reveals the fact OP doesn't even know what MTProto is.

**Comment by habnabit** [comment]
rude af

**Comment by KylinWu** [comment]
Thanks @stek29,  It's work!

**Comment by jadigar** [comment]
@OwnageIsMagic А причем тут es6, если проект весь кривой? это даже не альфа.

**Comment by OwnageIsMagic** [comment]
@jadigar год назад он был ещё норм
