### ISSUE TITLE
MtProto 2.0

### ISSUE THREAD

**Issue by AlexStrNik** [zerobias/telegram-mtproto#133]
Is this module compatible with telegram MtProto protocol 2.0?

**Comment by zerobias** [comment]
Not yet, but planned
Telegram will maintain the first version of protocol for some time, so we have time to upgrade

**Comment by lifehome** [comment]
Is there any update on this?

**Comment by ip** [comment]
@zerobias Do you know how long they'll keep it?

**Comment by zealotrahl** [comment]
@zerobias any updates?

**Comment by wfjsw** [comment]
For production usage, I would recommend any tdlib bindings. :/
