### ISSUE TITLE
dc-configurator findById doesn't work if dcId is a string

### ISSUE THREAD

**Issue by insprintorob** [zerobias/telegram-mtproto#135]
The findById call in /src/service/dc-configurator.js line 50 (latest master 7084e5e181b4ee565ebde56edb8f3aac66c69daa) will return undefined if dcId is a string. My testing showed that sometimes it was a string, sometimes it was an integer.

When it returns undefined, url becomes false further down the stack and requests stop working.

I'm making a fix to force dcId to be an integer when being passed to findById(). This fixes my issue locally.

Pull request #134

**Comment by zerobias** [comment]
Recent (2.x & 3.x) branches of the project work slightly different in this place but thanks 👍

**Comment by zerobias** [comment]
Merged #134
