### ISSUE TITLE
How to Update Handling?

### ISSUE THREAD

**Issue by JosefJezek** [zerobias/telegram-mtproto#136]
Could you add support for easy update handling?

As pyrogram lib...

```py
def callback(update):
    print(update)

client = Client(session_name="example")
client.set_update_handler(callback)
```

https://github.com/pyrogram/pyrogram/wiki/Update-Handling

Thank you :wink:

**Comment by danog** [comment]
github.com/danog/MadelineProto supports update handling, secret chat, phone calls, and much more!
Why don't you check it out ;)

**Comment by goodmind** [comment]
Duplicate of #40
