### ISSUE TITLE
Failed login is saved as success in storage

### ISSUE THREAD

**Issue by AndreasGassmann** [zerobias/telegram-mtproto#139]
I noticed that even if the signin was unsuccessful (wrong code for example), the "storage.json" still gets generated with `signedin = true`. This causes the program to assume the login was successful on the next execution, even though it wasn't. Is this something that is intended? I think this should be handled by the library and is probably a bug. (Save only if login is successful)

**Comment by zerobias** [comment]
Oops, edge case, I didn't think about it

**Comment by eboblin** [comment]
Probably it relates to some issues mentioned before, where code got hung in an infinite await and only storage deletion helped. Hope this bug to be resolved.

**Comment by Fuzzyma** [comment]
I have another problem where a successfull login is saved and can be used for a few hours.
But when I come back the next day, I have to delete the storage and require a new code.
I dont think that can be right. Other telegram clients dont need a code for every new day, too

**Comment by OwnageIsMagic** [comment]
Its a known issue

**Comment by Fuzzyma** [comment]
Please link me to the corresponding issue then

**Comment by AndreasGassmann** [comment]
https://github.com/zerobias/telegram-mtproto/issues/99
