### ISSUE TITLE
http instead of https in dc-configurator

### ISSUE THREAD

**Issue by cipher-code** [zerobias/telegram-mtproto#141]
On this line https://github.com/zerobias/telegram-mtproto/blob/master/src/service/dc-configurator.js#L52

You're using http instead on https. Is this intended?

**Comment by tulir** [comment]
Most likely yes. Telegram made their own client-server crypto rather than being sensible and using TLS.

**Comment by zerobias** [comment]
Yes, telegram is using http because it provides its own encryption level

Btw, on the third branch http or https is chosen on the fly because webogram servers are used https

https://github.com/zerobias/telegram-mtproto/blob/feature/mtproto3/packages/telegram-mtproto/src/config-check/dc.js#L58
