### ISSUE TITLE
Custom transport layer

### ISSUE THREAD

**Issue by skyne98** [zerobias/telegram-mtproto#147]
Hello there!

I was wondering if it is possible to implement my own transport layer?
For example, I wanted to use MTProto end-to-end for my P2P chat project, because of it's reliability and safety.

So, is it possible? Having glanced at the sources, I would say that there is no distinct interface for implementing a new transport layer.

Thanks!

**Comment by zerobias** [comment]
Hi! It pretty interesting question) Mtproto itself has a lot of layers of cryptography protection, so the same level of security could be reached only with mtproto own layers. But, technically it possible, as mtproto can work with any suitable transport.

Right now project isn't ready for layer switching, but I'm going to improve that in near future

**Comment by OwnageIsMagic** [comment]
Any real reason to choose mtproto?

**Comment by skyne98** [comment]
At least it's name suggests it's about telegram's MTProto. I may be wrong.
I prefer using it because I think it may be on of the main reasons of telegram's excellent stability.

**Comment by OwnageIsMagic** [comment]
telegram's excellent stability™ exclusively provided by thing named TCP (transport layer) and small packet size (because its a binary protocol)
