### ISSUE TITLE
Unhandled rejection Error: MT[406] NETWORK_BAD_REQUEST: http://149.154.167.51/apiw1

### ISSUE THREAD

**Issue by ChairmanMeow** [zerobias/telegram-mtproto#155]
I am getting this error when attempting a signup.
Does anyone know the reason for this? It seems like the datacenter IP is outdated?

![image](https://user-images.githubusercontent.com/1448407/36737748-63543860-1c0e-11e8-9ab0-15783300ea82.png)

**Comment by nagashik** [comment]
have you solved this truble? I have the same error and can't solve it.

**Comment by cook1e-monster** [comment]
new Promise((resolve, reject) => {
      .... promise MTProto .....

     .... create a timeout (if the mtproto don't return the resolve) and return resolve({code: errorCode, message: 'your message error" })

})

**Comment by cook1e-monster** [comment]
my solution for meteorjs but can work with nodejs

`import { MTProto } from 'telegram-mtproto'
import Storage from './Storage'

import { check, Match } from 'meteor/check'
import { logger } from '/imports/api/logger/logger'

export default class Telegram {
    constructor({ appId, hash, cookie = {} }) {
        check(appId, Number)
        check(hash, String)
        Match.Maybe(cookie, Object)

        this.__storage = new Storage(cookie)

        const server = { webogram: true, dev: false }

        const api = {
            invokeWithLayer: 0xda9b0d0d,
            layer: 57,
            initConnection: 0x69796de9,
            api_id: appId,
            app_version: '1.0.1',
            lang_code: 'en'
        }

        this.__appId = appId
        this.__hash = hash

        this.__connector = MTProto({ api, server, app: { storage: this.__storage } })
    }

    /* auth */
    getAuthCode(phone) {
        check(phone, String)

        const config = {
            phone_number: phone,
            current_number: false,
            api_id: this.__appId,
            api_hash: this.__hash
        }

        logger.info('called getAuthCode with options ', config)
        try {
            const { phone_code_hash } = Promise.await(this.__connector('auth.sendCode', config))
            return { phoneCodeHash: phone_code_hash, cookie: this.getCookie() }
        } catch (error) {
            throw new Meteor.Error(500, 'Telegram getAuthCode error: ', error)
        }
    }

    signIn({ phone, phoneCode, phoneCodeHash }) {
        check(phone, String)
        check(phoneCode, String)
        check(phoneCodeHash, String)

        const config = {
            phone_number: phone,
            phone_code_hash: phoneCodeHash,
            phone_code: phoneCode
        }

        logger.info('called signIn with options ', config)
        try {
            const res = Promise.await(this.__connector('auth.signIn', config))

            return { profile: res }
        } catch (error) {
            throw new Meteor.Error(500, 'Telegram signIn error: ', error)
        }
    }

    getCookie() {
        return this.__storage.storeToJSON()
    }

    /* METHODS */

    //promise resolver (hack bug unhandle promises)
    request(query, params) {
        return new Promise((resolve, reject) => {
            this.__connector(query, params)
                .then(result => {
                    return resolve(result)
                })
                .catch(error => {
                    return resolve(error)
                })

            Meteor.setTimeout(function() {
                return resolve({ code: 500, message: 'timeout' })
            }, 10000)
        })
    }

    getChats() {
        return Promise.await(this.request('messages.getDialogs', {}))
    }

    getChatHistory(chatId = 312274485) {
        const max = 400
        const limit = 100
        let offset = 0
        let full = [],
            messages = []

        const history = Promise.await()

        console.log(history)
        //messages = history.messages.filter(filterLastDay)
        // full = full.concat(messages)

        // messages.length > 0 && (offset = messages[0].id)
        // messages.length > 0 && console.log(offset, messages[0].id)
    }
}
`

**Comment by JRakhimov** [comment]
@cook1e-monster Why you use resolve for catching error instead of reject? Can you explain pls?
