### ISSUE TITLE
Can't get photos

### ISSUE THREAD

**Issue by extremecodetv** [zerobias/telegram-mtproto#156]
I try get chat or user avatars from dc2 (method: upload.getFile), but method always caught exception
> [4.319] Error 400 LOCATION_INVALID 2 2

code is very simple
```js
const response = await this.client('upload.getFile', { location: fileLocation }); 
```
inputFileLocation is actual and received just before requesting an file.
e.g.:
```
local_id:528821
secret:"8934288278545200272"
volume_id:"223034662"
```

#35 #106 A similar problem, but it remained unresolved

Any advice?

**Comment by extremecodetv** [comment]
Problem solved by adding valid type parameter to field 
```js
fileLocation._ = 'inputFileLocation';
```

Guys, can you note this important feature of working with your project in the readme, and not somewhere far in FAQ. Just this thing is not too obvious, and probably causes a lot of problems.

Thanks

**Comment by goodmind** [comment]
read wiki https://github.com/zerobias/telegram-mtproto/wiki/FAQ
