### ISSUE TITLE
Is that possible to receive new messages by subscribing on some event?

### ISSUE THREAD

**Issue by NikitaKA** [zerobias/telegram-mtproto#157]
I want to subscribe to some event and listen to new messages instead of long polling. Is that possible to do with this library?

**Comment by NikitaKA** [comment]
Guys, no one receiving messages here and don't know anything about no-long-polling updates?

**Comment by iam-medvedev** [comment]
Use updates.getState
https://core.telegram.org/api/updates#update-status
