### ISSUE TITLE
Error sending message to chat

### ISSUE THREAD

**Issue by AuroRacing** [zerobias/telegram-mtproto#158]
Want to send a message by this method:
const result = await telegram('messages.sendMessage', {
	peer: { "_": "inputPeerChat", "chat_id": 274300600 },
	message: 'Hello, my chat!',
	random_id: Math.round(new Date().getTime() / 1000)
});

but receive the error **CODE#400 PEER_ID_INVALID**, what could be the problem?

**Comment by OwnageIsMagic** [comment]
# PEER_ID_INVALID

**Comment by AuroRacing** [comment]
Could you give an example of how to make a function correctly?

**Comment by OwnageIsMagic** [comment]
Hou you got this id?

**Comment by AuroRacing** [comment]
TL-Schema,
but if you specify inputPeerUser and user ID then everything works
