### ISSUE TITLE
'channelParticipantsSearch' filter missing

### ISSUE THREAD

**Issue by Kati3e** [zerobias/telegram-mtproto#159]
I'm not seeing this filter included in this library, any chance this could be added soon? 

I'm sorting a channel's user list by most inactive users (based on "was_online") and currently I'm only able to fetch 10k users from the '**channelParticipantsRecent**' filter. I'm guessing that's the limit for that filter? With '**channelParticipantsSearch**' we can fetch the entire user list however, as if there is no filter. I'm working with a huge supergroup and need a way to fetch the entire list, any work arounds here?

Here are the core docs for '**channelParticipantsSearch**'
https://github.com/wfjsw/telegram-core-docs/blob/380c7b44741d7697a60bcf0ac8692de544a6dcd4/constructor/channelParticipantsSearch.md

**Here is what I'm trying to accomplish:** _(How it's done in Python with the Telethon library)_
https://github.com/LonamiWebs/Telethon/blob/master/readthedocs/extra/examples/chats-and-channels.rst#retrieving-all-chat-members-channels-too

### EDIT:
I see now that the 10k limit works across all filters and is imposed in core. I am still interested in the '**channelParticipantsSearch**' filter however, perhaps it could search for only users with certain offline statuses or by 'was_online'?

**Comment by goodmind** [comment]
You can use latest schema

**Comment by goodmind** [comment]
You can specify schema field with require from latest json schema

**Comment by Kati3e** [comment]
Using schema 74 from [https://github.com/stek29/tl-schema/tree/master/l074](https://github.com/stek29/tl-schema/tree/master/l074): 

**My Test Code:**
```javascript
const schema74 = require('./schema/schema74.json');

const server = {
  dev: false
};

const api = {
  layer         : 74,
  initConnection: 0x69796de9,
  api_id        : config.api_id
};

const app = {
  storage: new Storage('./storage.json')
};

const client  = MTProto({ server, api, app, schema74 });
```

**Results in the same issue:**
```
updates.getState
-------------------
{ _: 'updates.state',
  pts: 13067,
  qts: 0,
  date: 1520262534,
  seq: 1102,
  unread_count: 68 }

channels.getParticipants
----------------------------
Encrypted request failed Error: Constructor not found: 773059779 75 562312134
    at Deserialization.fetchObject (D:\Work\mtproto-kat\node_modules\telegram-mt
proto\lib\tl\index.js:470:15)
    at Deserialization.fetchVector (D:\Work\mtproto-kat\node_modules\telegram-mt
proto\lib\tl\index.js:396:26)
...
```

Is this perhaps related to the **server** I'm using and the fact that the **_latest_** [schema](https://github.com/stek29/tl-schema/tree/master/l074) only has 'Android/iOS' and 'Webogram' listed?

I tried setting **webogram** to true on the **server** but got the same results. So I'm kinda lost again. 

I am also still uneducated on exactly what '**initConnection**' is and when that would need to be changed. Am I going to have to construct my own from [here](https://core.telegram.org/method/initConnection) and use it instead? If so, any tips you can give me for the **params**?

Thanks for pointing me the right directions!

**Comment by goodmind** [comment]
It's shorthand object property syntax
