### ISSUE TITLE
Errors on different actions

### ISSUE THREAD

**Issue by terrasoff** [zerobias/telegram-mtproto#164]
I use **telegram-mtproto@3.0.6** (cuz on 3.1.22 all my requests hang/don't work).
Some actions works. I can (for the instance):
- send code
- sign in
- create channel
- join channel
...

Bus some actions don't work, like
- get channel participants
- create chat
- get chats
...

I fill all parameters according documentation for (current) **layer 23**. 
And each time i get same error `Error undefined undefined 2 2`

How to debug it and figure out what is an error, how to fix it?

**Comment by OwnageIsMagic** [comment]
Layer 23 is outdated as all of the official docs
Browse issues in this repo for more info

**Comment by terrasoff** [comment]
@OwnageIsMagic would be great to provide some links here if you know certain issues. Otherwise i'll find it later manually and leave it here. Thanks for clarifications!
