### ISSUE TITLE
Failed to minify code in React app

### ISSUE THREAD

**Issue by calogar** [zerobias/telegram-mtproto#165]
Hello. I m trying to use this package in my React app, and when I run `npm run build` to create a production build, I get the following error:

```
Failed to minify the code from this file:

        ./node_modules/telegram-mtproto/es/bin.js:4

Read more here: http://bit.ly/2tRViJ9
```

It seems that the package is not being compiled and published in ES5. Could you publish the package pre-compiled, or should I try to search for another solution?

**Comment by zerobias** [comment]
Hi, you probably need next branch of uglify-js, https://www.npmjs.com/package/uglify-es 

It seems that compilation which we have is not enough, but recently I found a way to make it es5 friendly, going to fix that in next update

**Comment by StarNeit** [comment]
I received same error when production build this MTProto package.
Is there any solution now, @calogar @zerobias ?
Thank you for your help.

**Comment by StarNeit** [comment]
my mtproto version is 
"version": "2.2.8"
