### ISSUE TITLE
TypeError: MTProto is not a function

### ISSUE THREAD

**Issue by ThatBrianDude** [zerobias/telegram-mtproto#168]
just installed both required modules at their latest version and ran the script.

**Comment by ThatBrianDude** [comment]
fixed this by modifying the first line from:

`const MTProto = require('telegram-mtproto')`

to:

const MTProto = require('telegram-mtproto').MTProto

which is weird because the module exports that function by default...

**Comment by OwnageIsMagic** [comment]
it's not weird
Close this issue, please

**Comment by ThatBrianDude** [comment]
When your examples throw errors there is an issue. Please update them first

**Comment by OwnageIsMagic** [comment]
@ThatBrianDude rtfm

**Comment by ThatBrianDude** [comment]
My bad, I must have removed the { } without noticing because I copy pasted the example from here: 
 
https://github.com/zerobias/telegram-mtproto/blob/master/examples/node-storage.js

Not sure what happened there, I apologize
