### ISSUE TITLE
how could I change mtproto servers?

### ISSUE THREAD

**Issue by nagashik** [zerobias/telegram-mtproto#173]
I would like to use mtproto proxy servers (mtproxyd) to connect to telegram network.
how could I change default mtproto servers?

**Comment by royalrover** [comment]
I resolve it by modify the source code, first get the nearest dc, and connect this one.

**Comment by KylinWu** [comment]
@royalrover Which mtproto library version do you use?

**Comment by royalrover** [comment]
3.1.3

**Comment by nagashik** [comment]
@royalrover what file should I change in source code?

**Comment by royalrover** [comment]
/lib/service/api-manager/index.js
 invokeNetRequest method
```
networker = yield _this5.mtpGetNetworker(x);
```
x is the nearest dc, and  make sure the file lib/config-check/dc.js ， the number of  the nearest dc is"x"
