### ISSUE TITLE
Simplify tl usage

### ISSUE THREAD

**Issue by zerobias** [zerobias/telegram-mtproto#18]
When using library, we should not have to deal with TL at all

**Comment by awadesmoline** [comment]
@zerobias please how do we even deal with it at present. I found not docs on it.  I get this error when I try passing in a list of user IDs 
```Error: Invalid object for type InputUser```

**Comment by goodmind** [comment]
https://github.com/zerobias/telegram-mtproto/wiki/FAQ

**Comment by awadesmoline** [comment]
thanks @goodmind.
