### ISSUE TITLE
join to chat group

### ISSUE THREAD

**Issue by fiftythreecorp** [zerobias/telegram-mtproto#180]
How do I enter the chat using the chat name (@chatname)?

I tried
`client('channels.joinChannel', {
    name: 'chatname' // or '@chatname'
    })`

But I get an error "CHANNEL_INVALID"

Maybe I should get chat_id (int)? How can I do this using the chat name?

**Comment by mehrzad3** [comment]
you should resolve channel name
`var result = await channels.resolveUsername('chatname');`
then you should make peer from resolved data : 
 `   var peer = {
      '_': "inputPeerChannel",
      'channel_id': result.chats[0].id,
      'access_hash': result.chats[0].access_hash
    }`
then you can join channel with this peer
`channels.join(peer);`
