### ISSUE TITLE
How to use a proxy?

### ISSUE THREAD

**Issue by fiftythreecorp** [zerobias/telegram-mtproto#182]
My server is in Russia, so access to telegram is blocked. How to use a proxy in a telegram-mtproto?

**Comment by OwnageIsMagic** [comment]
make vpn tunnel as default route

**Comment by fiftythreecorp** [comment]
The telegram-mtproto uses "axios" for requests. In this library you can not use the socks5 proxy server. With HTTPS proxy also a problem..  Maybe someone has a solution?

**Comment by fiftythreecorp** [comment]
I get an error when I try to use a proxy

`Error: write EPROTO 47031583164544:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

(node:981) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by wfjsw** [comment]
It is fine to make use of HTTP_PROXY, HTTPS_PROXY and ALL_PROXY variable just as curl.

**Comment by mkliu** [comment]
@fiftythreecorp have you solved this?

**Comment by playofff** [comment]
Does anyone have a solution?

**Comment by gyn7561** [comment]
i find a solution .

var httpClient = require('telegram-mtproto/lib/http').default;

httpClient.defaults.proxy = {
    host: "localhost",
    port: 1080
}

**Comment by gyn7561** [comment]
@playofff @mkliu

**Comment by playofff** [comment]
@gyn7561 , thank u)

**Comment by Xandr2410** [comment]
@gyn7561 , i used your solution about proxy but i have error
Auth error write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:827:
 Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:827:

why i have her??
