### ISSUE TITLE
Error 400 CHANNEL_INVALID 2 1

### ISSUE THREAD

**Issue by hmborges** [zerobias/telegram-mtproto#185]
I'm trying to get some messages of a private channel, when I use the `chatHistory` function of the `chat-history.js` example as it is, passing as parameter the chat selected with `getChat` function it works perfectly. 
But when I set the `channel_id `and the `access_hash `manually it does not work and I get the `Error 400 CHANNEL_INVALID 2 1` .
I tried adding the -100 at the beginning of the `channel_id `but did not work as well and I did not found any other solution.
How can I solve it?

**Comment by goodmind** [comment]
what id?

**Comment by hmborges** [comment]
In peer object @goodmind 

```
chatExample = {
    id : -1001204273971,
    access_hash: 10040664572369783124
 }

const history = await client('messages.getHistory', {
      peer: {
        _          : 'inputPeerChannel',
        channel_id : chatExample.id,
        access_hash: chatExample.access_hash
      },
      ...
    })
```

**Comment by hmborges** [comment]
@goodmind do you have any idea of what could be the solution?

**Comment by hmborges** [comment]
It worked perfectly!! Thank you very much @Bannerets

**Comment by StarNeit** [comment]
Thank you @Bannerets
