### ISSUE TITLE
Pulling messages from a Channel, without having 2fa?

### ISSUE THREAD

**Issue by napindc** [zerobias/telegram-mtproto#187]
I have a node server, and I want to constantly monitor a private telegram channel that I’m in. When new messages are sent to the channel, I want my node server to take the text of that message and do something with it.

However, is this possible given all the examples have 2fa in it? I don’t want to pause my server every now and then, and rerun it with a new 2fa code.

**Comment by goodmind** [comment]
```js
client.bus.untypedMessage.observe(data => {});
```

**Comment by goodmind** [comment]
@napindc don't authenticate on each request

**Comment by goodmind** [comment]
@napindc there is examples without 2fa
