### ISSUE TITLE
Installation Example

### ISSUE THREAD

**Issue by JRakhimov** [zerobias/telegram-mtproto#189]
Hi guys, can anybody write a guide of how to install and run mtproto server?

**Comment by cook1e-monster** [comment]
https://glitch.com/edit/#!/join/86a74354-84b3-48fd-9e1c-b015f7464267

**Comment by JRakhimov** [comment]
[Here](https://github.com/JRakhimov/MTProto-Bot) is my example of using this lib with tlegram bots, you can check this out
