### ISSUE TITLE
Config validation

### ISSUE THREAD

**Issue by zerobias** [zerobias/telegram-mtproto#19]
The library has an extensive complex configuration, so the invalid values or incorrect config settings must throw an obvious error

**Comment by goodmind** [comment]
What would be considered invalid values? Like runtime type checking or what?

**Comment by zerobias** [comment]
@goodmind Yes, validation when creating the instance. It is quite cheap, just to check that the configuration includes the required fields, and don't contain any unknowns

**Comment by zerobias** [comment]
For example, webpack 2 does so
