### ISSUE TITLE
How to save api_id and api_hash on client securely? 

### ISSUE THREAD

**Issue by Mondei1** [zerobias/telegram-mtproto#190]
I'm currently working on a electron application and I don't know how to save my key that nobody can access it. Maybe I have to write a backend that's run on my server and handle all requests there.

But is there any way to do it **directly from the client**?

**Comment by VladimirEfstafiev** [comment]
Unfortunately (as far as I know) electron doesn't have source code protection. 
Have you heard about NW.js? If you want to secure your sources it will definitely help. 
[NW.js code protection mechanism.](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/)

**Comment by Mondei1** [comment]
Oh thanks, I will take a look at this. I think that will solve my problem.

**Comment by Mondei1** [comment]
@VladimirEfstafiev NW.js will not work. Because I'm currently developing a widget for something. So I think I have to develop a own backend for that.

**Comment by adavidof** [comment]
@Mondei1 
Hello, did you logged in to telegram API?
Could you please help me with it?

**Comment by Mondei1** [comment]
@adavidof Yeah, I was logged in. It's not that hard. Sorry for this late response, forget this here a little bit.

**Comment by adavidof** [comment]
@Mondei1, @zerobias

I use these versions:
```
"mtproto-storage-fs": "^0.3.1",
"telegram-mtproto": "2.2.2"
```

but on the node server(heroku) I got this error:
```
Error 401 AUTH_KEY_UNREGISTERED 2 1
```

with the same auth keys

what I missed?
