### ISSUE TITLE
Where i can see all methods?

### ISSUE THREAD

**Issue by Xandr2410** [zerobias/telegram-mtproto#191]
Hi friends, say me please Where i can see all methods , for example getChatUser etc.?

**Comment by Bannerets** [comment]
https://stek29.rocks/tl-schema/latest/

**Comment by Xandr2410** [comment]
getChatUser or getChatMember dont have?

**Comment by zqannnnn** [comment]
@Bannerets Thanks guy.I want the use channels.inviteToChannel to invite uses to my channel,but it don't work.Can this method be used?
Thank you very much!
