### ISSUE TITLE
I made a repo for reading telegram channel messages with little setup

### ISSUE THREAD

**Issue by abdhass** [zerobias/telegram-mtproto#196]
https://github.com/abdhass/telegram-channel-scraper 

Should provide some starting point for those stuck in using this library. 

(Admin: Apologies in advance if this is not allowed. My first repo aimed for others. I just thought i'd share my work after having trouble in using this library. Im sure others can benefit from this. )

**Comment by ismenc** [comment]
hello mate @abdhass,
Im also developing a kinda channel scraper project in my free time (but keeping the code for myself).
I will check out your project and try to give you a hand on whatever i can 😄 
Have a nice coding.

**Comment by JRakhimov** [comment]
Have you encountered a problem like `Encrypted request failed { Error: MT[406] NETWORK_BAD_REQUEST: http://149.154.167.51/apiw1`? Here is my [client ](https://github.com/JRakhimov/MTProto-Bot)based on bots as interface and everything works excellent except of this err, And this error pops up just like that, even when I do not use methods of MTProto... Can any one check out and give some advise?

**Comment by JRakhimov** [comment]
Bot uses Firebase Database as a storage, if some one need this implementation you can get it from [here](https://github.com/JRakhimov/MTProto-Bot/blob/master/src/mtproto/Storage.js)
