### ISSUE TITLE
Webogram

### ISSUE THREAD

**Issue by JRakhimov** [zerobias/telegram-mtproto#197]
What is webogram: true is really do?

**Comment by Bannerets** [comment]
It connects to

```
dc1: https://pluto.web.telegram.org/apiw1
dc2: https://venus.web.telegram.org/apiw1
dc3: https://aurora.web.telegram.org/apiw1
dc4: https://vesta.web.telegram.org/apiw1
dc5: https://flora.web.telegram.org/apiw1
```

**Comment by JRakhimov** [comment]
and what it gives to me? I have had suddenly error like `Encrypted request failed { Error: MT[406] NETWORK_BAD_REQUEST: http://149.154.167.51/apiw1` so I experimented with webogram and added my own servers from my.telegram.org and everything is okay
