### ISSUE TITLE
channels.readHistory not working

### ISSUE THREAD

**Issue by ismenc** [zerobias/telegram-mtproto#199]
Hello there,
I'm having a trhouble when trying to perform `messages.readHistory` and `channels.readHistory` either in *api-57* or *api-82*. 

<details>
     <summary>Outputs</summary>
 <p>

#### messages.readHistory

```
{
            "code": 400,
            "type": "PEER_ID_INVALID",
            "description": "CODE#400 PEER_ID_INVALID",
            "originalError": {
                "_": "rpc_error",
                "error_code": 400,
                "error_message": "PEER_ID_INVALID"
            }
        }
```
(im using the same peer than in a successful getHistory operation)

#### channels.readHistory

``` Error: No predicate undefined found ```
<br>
#### messages.readHistory

``` parse error Constructor not found: 2430458897 26304 2281 Error: Constructor not found: 2430458897 26304 2281 ```
(im using the same peer than in getHistory operation)

#### channels.readHistory

``` parse error Constructor not found: 2430458897 26304 3138 Error: Constructor not found: 2430458897 26304 3138 ```

```Encrypted request failed TypeError: Cannot read property 'toString' of undefined```
      </p></details>

Has anyone sort this problem?

**Comment by OYYMING** [comment]
Hey ismenc,
I tried the `messages.readHistory` method, and it works well in _api-57_.
I think maybe you should check if your params are in correct format.
BTW, these are what passed as parameters:
```
telegram('messages.readHistory', {
    peer: {
        _: "inputPeerUser",
        access_hash: "access_hash",
        user_id: 111111111,
    }
}
```

**Comment by ismenc** [comment]
Forgot to point that im trying to read a **channel** and im using **version 2.2.2**.
Im using the same format i usually do with getHistory, Example

```
peer: {
    _          : 'inputPeerChannel',
    channel_id : 1000333444,
    access_hash: '246767425009898989'
}
```
These values come from a chat in a previously performed getMessages operation.

Aditional failed attemps:

* Using user peer, with 'inputPeerUser' and user_id
* Using chat peer, with 'inputPeerChat' and chat_id

**Comment by ktjd123** [comment]
Is there any updates?

**Comment by ismenc** [comment]
> Is there any updates?

@zerobias is recomending on readme.md to use Telethon.
So this library is probably not getting supported anymore. I would not recommend you to use it
