### ISSUE TITLE
Implement updates manager

### ISSUE THREAD

**Issue by zerobias** [zerobias/telegram-mtproto#20]
The mtproto library should handle data updates on its own

**Comment by zerobias** [comment]
https://github.com/goodmind/treact/issues/10

**Comment by stek29** [comment]
Maybe it would be better to make a separate library which would help with things like this, 2FA and any other things which may be common in almost any app?

**Comment by zerobias** [comment]
@stek29 sounds reasonable

**Comment by zerobias** [comment]
Looks like this feature needs deep type handling, which depends on project architecture

**Comment by homjke** [comment]
Any progress ?

**Comment by munrocket** [comment]
Where we can find this functionality? Maybe in another library?

**Comment by munrocket** [comment]
Maybe this will help with message update.

“IdleTasks appeared because Ping messages are needed from time to time or the server will drop the client. The blocking receive() are a product of my inability to control async receive() for very short periods.”
