### ISSUE TITLE
How to fix invalid peer id

### ISSUE THREAD

**Issue by kingqi** [zerobias/telegram-mtproto#209]
Got this error:
> Error 400 PEER_ID_INVALID 2 5

But i am not using peer id as parameter, what is this error means?

Here is my code:
```sh
const getChat = async () => {
  const getInfo = await client('messages.getFullChat',{
    chat_id:200275452
  })
  console.log(getInfo);
}
```

library version: 3.0.6

**Comment by azayek5** [comment]
You ever figure out what was going on?
