### ISSUE TITLE
Flood wait!

### ISSUE THREAD

**Issue by JYF3721** [zerobias/telegram-mtproto#215]
When I used auth. sendCode, I didn't respond for a long time, and then I tried to call another method and returned the following warning, stating that I was using version 3.2.11
![image](https://user-images.githubusercontent.com/17564581/46792197-5b370400-cd75-11e8-8000-a60306813343.png)

**Comment by slinker-hiwa** [comment]
Version 3.2.11 is not good, let try telegram-mtproto@3.0.5-unstable, i am using this version. don't have any error.
For this error. Maybe you call so much request. Please check your code.

**Comment by slinker-hiwa** [comment]
1. auth.sendCode and auth.signIn must be in the same object MTProto. Without disconnection

2. dev DC and live is different, so when you config {dev: true}, all API will call to dev DC,
your phone didn't register on this DC

So please catch response API auth.sendCode field phone_registered: false or undefined.

if phone_registered = false, use "auth.signUp" instead "auth.signIn" with same params.
Have fun.
