### ISSUE TITLE
New Telegram API Schema

### ISSUE THREAD

**Issue by GiverDead** [zerobias/telegram-mtproto#226]
In telegram API added few new constructors like inputPeerContact and inputPeerForeign
[https://core.telegram.org/method/messages.sendMessage](url) 
How i can send message to Dialog (not chat) with this constructors?
i tried to use downloaded Schema 
[https://core.telegram.org/schema/json](url) and [https://core.telegram.org/schema/mtproto-json](url)
but have error Constructor not found: 3251786849 6 34875619 (like this. Not correct)
In teltgram docs last layer is 2-23 but i seen 57,62,71.. why numbers are different?

**Comment by goodmind** [comment]
this is old schemas

**Comment by yoolsylva** [comment]
Please check new schemas at: https://tjhorner.com/tl-schema
