### ISSUE TITLE
我第二次使用API进行登陆后，返回了 error 400 PHONE_NUMBER_BANNED ，我没有做其他的操作啊 不知道为什么 

### ISSUE THREAD

**Issue by SoTiger** [zerobias/telegram-mtproto#230]

**Comment by SoTiger** [comment]
错误代码  第一次登陆成功 ，我没有使用logout 正常退出, 而是直接kill了登陆进程 然后再次通过api登陆后 报这样的错误
[46.684] Error 400 PHONE_NUMBER_BANNED 2 5
failed  { code: 400,
  type: 'PHONE_NUMBER_BANNED',
  description: 'CODE#400 PHONE_NUMBER_BANNED',
  originalError:
   { _: 'rpc_error',
     error_code: 400,
     error_message: 'PHONE_NUMBER_BANNED' } }

**Comment by zRattly** [comment]
the phone number is banned from telegram
