### ISSUE TITLE
Nearly impossible usage of types with optional parameters

### ISSUE THREAD

**Issue by zerobias** [zerobias/telegram-mtproto#25]
Flags fields demands to be preprocessed before type will created

The user should be able to leave optional parameters unspecified

https://github.com/zerobias/telegram-mtproto/issues/24#issuecomment-287586971

`messages.sendMessage` with complicated type

```
messages.sentMessage#d1f4d35c id:int date:int pts:int seq:int = messages.SentMessage;
messages.sentMessageLink#e9db4a3f id:int date:int pts:int seq:int links:Vector<contacts.Link> = messages.SentMessage;
---functions---
messages.sendMessage#4cde0aab peer:InputPeer message:string random_id:long = messages.SentMessage;
```

should allow to be invoked this way

```javascript
client('messages.sendMessage',{ 
    peer: {'_': 'inputPeerChat', chat_id:80247363},
    message: 'Hello msg from lib'}
)
```

**Comment by wfjsw** [comment]
https://github.com/zerobias/telegram-mtproto/issues/24#issuecomment-287586971

It seems this error is not caused by flag missing. I have calculated the flag according to the code located in telegram-tl-node library but I still get is issue. I attempted to call messages.checkChatInvite and it succeeded.

The error probably is caused by `inputPeerChat` section.

**Comment by zerobias** [comment]
It seems like that issue was gone in the recent dev version. Will collect some feedback and close this asap

**Comment by wfjsw** [comment]
Any possible way to install the master branch build with npm?

**Comment by wfjsw** [comment]
And, I noticed there is a field named `access_hash` in both inputPeerUser and inputChannel. I have no idea where can I get it with bot account. Will this be handled internally or I have to take care of that?

**Comment by wfjsw** [comment]
OK dev branch lgtm.

**Comment by zerobias** [comment]
@wfjsw For the note: `access_hash` always come with peer object itself
