### ISSUE TITLE
Session in Node

### ISSUE THREAD

**Issue by Lord-Protector** [zerobias/telegram-mtproto#27]
How can I save session in node to use it in future? I use RethinkDB. I don't find how to do it in example code. I think it saves it in cookie, but not sure.

I use pure JS (not TS, Babel, etc) so I can't use Interface like it's shown in readme.

**Comment by Lord-Protector** [comment]
```
module.exports.get = function (key) {
	return r.db('testdb').table('testtable').get(key).values().run().then(function (data) {
		return data[1];
	}).error(function (error) {
		console.warn(erroe)
	});
};

module.exports.set = function (obj, val) {
	return r.db('testdb').table('testtable').insert({ obj: obj, val: val}, { conflict: 'update' });
};

module.exports.remove = function (keys) {
	return r.db('testdb').table('testtable').getAll(r.args(keys)).delete();
};

module.exports.clear = function () {
	return r.db('testdb').table('testtable').delete();
};
```

**Comment by zerobias** [comment]
@Lord-Protector Glad to hear that it was easy 😄
Also, after this issue, I began to make AsyncStorages more lucid and user-friendly

**Comment by Lord-Protector** [comment]
@zerobias as offtopic question: Is there any docs with available methods? I just use `client('mtprotoMethod, {})` now.

**Comment by zerobias** [comment]
@Lord-Protector yes, it is. https://core.telegram.org/schema Brief and outdated, but it is better than nothing

**Comment by Lord-Protector** [comment]
@zerobias в принципе вот ещё неплохая документация, но она частично на русском:
https://core.telegram.org/tdlib/Java_API

**Comment by sadeghtkd** [comment]
@zerobias @goodmind  Why I got this error when I using storage : 
`(node:9756) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: get Networker without dcID`

My code : 
`import MTProto from 'telegram-mtproto'
import myStorage from './myStorage'

const readline = require('readline');
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});
//'+9647732069285'
const phone = {
  num : '+989157690095',
  code: '74636'
}

const api = {
  layer          : 57,
  initConnection : 0x69796de9,
  api_id         : 19896
}

const server = {
  dev: false //We will connect to the test server.
}           //Any empty configurations fields can just not be specified

const client = MTProto({ server, api , app : {storage: myStorage} })//
var  phone_code_hash ={}

async function connect(){
   phone_code_hash  = await client('auth.sendCode', {
    phone_number  : phone.num,
    current_number: false,
    api_id        : 19896,
    api_hash      : 'b43316c048960d6a599d4fe3497c3610'
  })
  
  console.log(phone_code_hash.phone_code_hash);
  //console.log('signed as ', user)
}
async function signIn(smscode)
{
	const { user } = await client('auth.signIn', {
		phone_number   : phone.num,
		phone_code_hash: phone_code_hash.phone_code_hash,
		phone_code     : smscode
	  });

	console.log('signed as ', user)
	resolveUsername('mashreghnews_channel');
}

connect()

rl.question('Enter telegram code sent by sms? ', (answer) => {
	signIn(answer);
  
  rl.close();
});

async function resolveUsername(userName)
{
	const  {resp}  = await client('contacts.resolveUsername', {username : userName});

	console.log('resolved ', resp)
}
`

and my storage module : 
`var r = require('rethinkdbdash')();

module.exports.get = function (key) {
	return r.db('telegramtest').table('testtable').get(key).values().then(function (data) {
		return data[1];
	}).error(function (error) {
		//console.warn(error)
	});
};

module.exports.set = function (obj, val) {
	return r.db('telegramtest').table('testtable').insert({ obj: obj, val: val}, { conflict: 'update' });
};

module.exports.remove = function (keys) {
	return r.db('telegramtest').table('testtable').getAll(r.args(keys)).delete();
};

module.exports.clear = function () {
	return r.db('telegramtest').table('testtable').delete();
};`

**Comment by zerobias** [comment]
@sadeghtkd This is a bug in the lib, sorry for that. I already fix it in the 3.x branch version, in the 2.x one you can slightly correct the `server` configuration:
```js
const server = {
  dev: false,
  webogram: true, //This option allows you to use undocumented additional servers
                  //used by the official web client
}
```

**Comment by sadeghtkd** [comment]
@zerobias Thanks , I updated the lib to ver 3.0.6 but still giving this error : 
![image](https://cloud.githubusercontent.com/assets/5601781/26296387/bd65ff22-3ee3-11e7-9dc0-f9960adef7c9.png)
can you provide a working example for saving session that user doesn't need login again?
