### ISSUE TITLE
Can't get photos not from my datacenter

### ISSUE THREAD

**Issue by L11R** [zerobias/telegram-mtproto#35]
I try to get avatar (`upload.getFile`) from dc4 and dc3, but I can't:
```
{ code: 303,
  type: 'FILE_MIGRATE_4',
  description: 'CODE#303 FILE_MIGRATE_4',
  originalError: 
   { _: 'rpc_error',
     error_code: 303,
     error_message: 'FILE_MIGRATE_4' } }
```
I think lib has hardcoded my data center (dc2) and by default ignore custom dc_id.

**Comment by goodmind** [comment]
add third argument to API call:
```
{ dcID: 4, fileDownload: true, createNetworker: true }
```

**Comment by Lord-Protector** [comment]
@goodmind thanks, it's works, I got only one error (instead of decades) `Error 400 LOCATION_INVALID 2 2`

**Comment by goodmind** [comment]
@Lord-Protector It looks like photo doesn't exists

**Comment by zerobias** [comment]
My current work on mtproto3
