### ISSUE TITLE
Code 303 errors

### ISSUE THREAD

**Issue by goodmind** [zerobias/telegram-mtproto#36]
We should handle migration errors here:
[error-cases.js:97](https://github.com/zerobias/telegram-mtproto/blob/develop/src/service/api-manager/error-cases.js#L97)

Also uncomment FLOOD_WAIT

**Comment by goodmind** [comment]
It looks like error handling in [request.js](https://github.com/zerobias/telegram-mtproto/blob/master/src/service/api-manager/request.js) not works

**Comment by zerobias** [comment]
Seems like it's not a problem anymore (yay :sweat_smile:)
