### ISSUE TITLE
More docs required - storage key names / types

### ISSUE THREAD

**Issue by leonerd** [zerobias/telegram-mtproto#41]
The toplevel README makes a brief mention of the `AsyncStorage` API that can be used to persist values. However, it doesn't go into any detail about, for example, what key names are used by the library and what types their values are expected to be.

By observation of my local copy, I have determined at least the following key names:

    TODO: storage gets dc
    TODO: storage gets dc2_auth_key
    TODO: storage gets dc2_server_salt

I can likely guess that there may be other key names relating to other DC numbers also. But what else?

Additionally I suspect there is a bug in the documentation of the `set` method, which is currently documented as:

> set(obj: any): Promise<void>;

However, in my observation the method is invoked with two values - a string key, and an associated value; for example:

    TODO: storage sets dc2_server_salt to c5cc98f309474772

I expect the docs should have said

    set(key: string, obj: any): Promise<void>;

**Comment by zerobias** [comment]
Tried to explain this thing more 7c5fec822becd82d9ec07ac1520d0be7b6905f49

**Comment by wfjsw** [comment]
The `file-storage` is not being exported to `plugins`

**Comment by zerobias** [comment]
@wfjsw Yes, that's the problem, because if we do, then browser builds immediately fall due to lack of the fs. Now I'm looking for compromise solutions.

**Comment by wfjsw** [comment]
And it fails to write anything to disk, so far.

**Comment by zerobias** [comment]
Proper realization going to be much larger, and right now module needs to have valid JSON object before the start.
[CI testing](https://github.com/zerobias/telegram-mtproto/blob/develop/test/node.test.js#L26) works with that [example](https://github.com/zerobias/telegram-mtproto/blob/develop/test/storage.json)

**Comment by wfjsw** [comment]
@zerobias I know that, but probably you should `cat` that file after finish processing. I can find only `{}` there.

**Comment by goodmind** [comment]
@wfjsw this is because `file-storage` don't write anything to file... 

https://github.com/zerobias/telegram-mtproto/blob/develop/src/plugins/file-storage/simple-file-storage.js#L67

/cc @zerobias lol

**Comment by zerobias** [comment]
@goodmind No, its write data every 0.5s) But I agree that's awful :smile:

**Comment by wfjsw** [comment]
I invoked `save()` manually with no luck.

**Comment by leonerd** [comment]
See also #45
