### ISSUE TITLE
  RangeError: Wrong length! Error. or Error: 400 PHONE_CODE_EXPIRED CODE#400 PHONE_CODE_EXPIRED

### ISSUE THREAD

**Issue by sajadghobadi** [zerobias/telegram-mtproto#42]
here is sample
when i receive activation code and use it to sign in telegram by below sample code get this error.
**RangeError: Wrong length!** 
use babel for transcompile to es5.
code : 

```javascript
const login = async () => {
  try {

    const phone = '+98........................'

    const info = JSON.parse(fs.readFileSync('code.json'));
    const code = info.phoneCode;
    const phone_code_hash = info.phone_code_hash;

    const res = await telegram('auth.signIn', {
      phone_number: phone,
      phone_code_hash,
      phone_code: code
    })

    const { user } = res
    const {
      first_name = '',
      username = ''
    } = user

    console.log('signIn', first_name, username, user.phone)
    return first_name
  } catch (error) {
    console.error(error)
  }
}
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RangeError: Wrong length!

**Comment by wfjsw** [comment]
You should check every constants to make sure they are valid first.

always surround **all** your codes with three `

**Comment by zerobias** [comment]
@sajadghobadi How did you receive a phone code hash from a file?
Looks like it does not exist at all

Hash is what you must inquire from the server

[Example](https://github.com/zerobias/telegram-mtproto/blob/master/test/node.test.js#L39)

**Comment by wfjsw** [comment]
@zerobias Probably he split the login process into two parts: getCode and signIn.

**Comment by sajadghobadi** [comment]
@zerobias and @wfjsw   thanks lot for response 
this error occurre for cheep!(sorry) mistake. i must pass phone_code_hash to signIn method but in truly i send undefined!!!

change and correct phone hash code to 
`const res = await telegram('auth.signIn', {
  phone_number: phone,
  phone_code_hash:phone_code_hash,
  phone_code: code
})`

# My final target is this : read messages from channel list(example:['channel1','channel2','chanell3'])
## for do this is run below step

1.  call auth.sendCode method and write _**phone_code_hash**_  to file named code.json
2. write manually **_activation code_** that i received in my phone  to file named code.json 
3. then i trying to login by those values in code.json by call auth.signIn (@wfjsw  you right exactly in split send code and login in to step)
4. but i get this error always  : **Error: 400 PHONE_CODE_EXPIRED CODE#400 PHONE_CODE_EXPIRED**

please help me if you can.
thnaks.
sorry for my bad en

**Comment by sajadghobadi** [comment]
@zerobias  you can't help?

**Comment by zerobias** [comment]
@sajadghobadi Have you used the code as string or number type? Phone, code and hash fields must be string, not number.


I think this code.json should fails
```json
{
  "code": 12345
}
```

So better to try this
```json
{
  "code": "12345"
}
```

**Comment by wfjsw** [comment]
@sajadghobadi
Hmm...Expired? You should try to understand it.
The main problem is that you are too slow to get you authenticated. Try to be quick next time.

However, depend on what you are doing, there is a rare case. According to https://t.me/MadelineProto/23
```
#UndocumentedAPIChangeOfTheDay 
Telegram automatically invalidates your login code if it is sent to any chat on telegram before the login, this problem can be avoided simply by appending or pretending some chars to the code.
Thanks to @usage_tg for finding that out.
```

Time to debug on your own.

**Comment by FragsterAt** [comment]
@sajadghobadi I also had such a error until I request code and sent the result within one connection

**Comment by wfjsw** [comment]
(also make sure that you are using the same auth keypair for auth)

**Comment by javeedrahman** [comment]
@FragsterAt how did you grab the code from telegram to the code, i am getting response only for phone_code_hash and phone_code sent from telegram official to my telegram chat.

I copied the login_code from app, try pasted in 

client("auth.signIn", {
    phone_number:   number,
    phone_code_hash: result.phone_code_hash,
    phone_code:      "39480",
}).then((result) => {
    console.log("User:", result);
});

But always getting PHONE_CODE_EXPIRED.

@wfjsw tried this but no luck appending or pretending return PHONE_CODE_INVALID
Some one please help.

_#UndocumentedAPIChangeOfTheDay 
Telegram automatically invalidates your login code if it is sent to any chat on telegram before the login, this problem can be avoided simply by appending or pretending some chars to the code.
Thanks to @usage_tg for finding that out._

**Comment by goodmind** [comment]
@javeedrahman please use three backticks for code blocks

**Comment by javeedrahman** [comment]
@goodmind okay sure got it.

**Comment by javeedrahman** [comment]
Here is the Sample code trying::

```
const phone = {
  num : '+9199999999999',
  code: '22222'
}
const config = {
  // NOTE: if you FORK the project you MUST use your APP ID.
  // Otherwise YOUR APPLICATION WILL BE BLOCKED BY TELEGRAM
  // You can obtain your own APP ID for your application here: https://my.telegram.org
  id  : 49631,
  hash: 'fb050b8f6771e15bfda5df2409931569'
}

var telegram = MTProto({
    layer: 57,
    api_id: config.id,
});

  const run = async ()  => {
      try {
        const { phone_code_hash } = await telegram('auth.sendCode', {
              phone_number  : phone.num,
              current_number: false,
              api_id        : config.id,
              api_hash      : config.hash
        })
        console.log('phone_code_hash', phone_code_hash)
        res = await telegram('auth.signIn', {
          phone_number: phone.num,
          phone_code_hash,
          phone_code  : "83118"
        })
        console.log('signIn', res)
        console.log('\n Logined as user')
        console.dir(res.user, { colors: true })
      } catch (err) {
        console.log('err', err)
      }
  }
  run()
```

**Comment by dundas** [comment]
Were you able to figure this out?

**Comment by onezens** [comment]
@dundas  https://github.com/zerobias/telegram-mtproto/issues/124#issuecomment-367972932

**Comment by terrasoff** [comment]
- They say if you are receive security code by sms and to telegram application then it will be expired. I don't reproduce it. Receiving code in telegram i still have valid security code and was able to sign in.
- Check the client instance, it should be same across whole application lifecycle.
- Client's configuration should define storage (where to put information about data center connection)
- If you are using different phone numbers clean up previously created storage (remove storage json file)
