### ISSUE TITLE
Options to disable nearest DC detection & force dc_id

### ISSUE THREAD

**Issue by wfjsw** [zerobias/telegram-mtproto#43]
According to https://t.me/MadelineProto/21

```
#UndocumentedAPIChangeOfTheDay 
Bots can't execute the help.getNearestDC method with layer 66 anymore, which kinda makes sense since most bot accounts are used from the same datacenter, but then again, a changelog would've been nice.
```

There is a high possibility that the lib breaks in this change, therefore better error_handling or an option should be implemented.

**Comment by goodmind** [comment]
What they mean by *bots* ?

**Comment by wfjsw** [comment]
By authorizing with `auth.importBotAuthorization` one can log in to a bot account and interact with a restricted set of command.

**Comment by goodmind** [comment]
@Lord-Protector I think that you can login with bot and then login with regular account and proxy advanced methods from bot to regular account

**Comment by wfjsw** [comment]
@Lord-Protector Nop there are still some extra feature that official Bot API can't provide, such as pulling off member list, group blacklist, group description etc. (in last few months we can even make bot add user to a group or join a group by link)

The main point to use this way is to avoid retarded official api server and talk to dc directly.

@goodmind That's the way https://github.com/pwrtelegram/pwrtelegram works.

**Comment by wfjsw** [comment]
Oh did I forgot that text-mention is available too :p

**Comment by Lord-Protector** [comment]
@wfjsw oh! Is it really can retrive FULL list of chat participants?

**Comment by Lord-Protector** [comment]
@goodmind I already do something like that. I use Bot API (and bot) as Update Handler and User-based bot for triggering some advanced methods (like adding to group, pinning etc.). But it require bot and user in group. So I wait update handler in you lib, to do fully autonomous user-based bots.

Don't understand you why I should proxy methods FROM bot TO user. Bot's have cuted API.

**Comment by wfjsw** [comment]
@Lord-Protector 
Try it out: https://github.com/pwrtelegram/pwrtelegram-app/raw/master/TMessagesProj/TMessagesProj-fat-release.apk

**Comment by wfjsw** [comment]
It seems the changes is to push the migration through error code.
