### ISSUE TITLE
Actual version of package in npm

### ISSUE THREAD

**Issue by rapkin** [zerobias/telegram-mtproto#44]
Hi, can you publish last stable version of this package on npm?
I have some troubles with old version (1.0.5) and i see v2 without large issues.

**Comment by goodmind** [comment]
It isn't published because we don't have all features done

**Comment by rapkin** [comment]
@goodmind ok, so how can i install this package in my project? i have some troubles with dependency: when i use something like `"telegram-mtproto": "zerobias/telegram-mtproto#mtproto2"` (in package.json) i have problems with import (directory _lib_ not exists in project). After that i tried to use this commands:
```
git clone https://github.com/zerobias/telegram-mtproto
npm run prepublish
npm link
cd ~/path/to/your-project/
npm link telegram-mtproto
```
after those manipulations i receive error: `Error: only one instance of babel-polyfill is allowed`

**Comment by goodmind** [comment]
`npm install --save telegram-mtproto@beta`

**Comment by rapkin** [comment]
@goodmind i have same error `Error: only one instance of babel-polyfill is allowed`.

**Comment by FragsterAt** [comment]
@rapkin , try to use git directly in package.json:
    "telegram-mtproto": "git+https://github.com/zerobias/telegram-mtproto.git#master"

**Comment by zerobias** [comment]
@rapkin Strange things, module does not use babel polyfill at all.

**Comment by rapkin** [comment]
I installed the version `2.2.8` from the npm and everything work well.
Thanks for the help.

**Comment by rapkin** [comment]
@zerobias hi, I very interested in this lib. How can I contact with you (or please contact with me)? Maybe I can help with this project (documentation, examples, etc)

**Comment by zerobias** [comment]
@rapkin Sorry, didn't look at the closed issues, you can write to me in Telegram @ZeroBias
