### ISSUE TITLE
More docs required - how to create API value objects

### ISSUE THREAD

**Issue by leonerd** [zerobias/telegram-mtproto#46]
When making API calls, it seems that simple types like integers and strings can be passed as native javascript types. It doesn't seem clear how to pass other types, for example, a value whose MTProto type name is `InputChannel`, as the parameter for `channels.getFullChannel`.

My previous code, based on `telegram.link` worked by

    client.channels.getFullChannel(new TelegramLink.type.InputChannel({props: {
      channel_id: id,
      access_hash: hash,
    }});

Using your `telegram-mtproto` the API call is made a different way, but I'm not sure how to construct the value required:

    client("channels.getFullChannel", {channel: BANANA})

What code do I write in `BANANA` above, given my channel ID and access hash values?

**Comment by goodmind** [comment]
```
const BANANA = {
   _: 'inputChannel',
   channel_id: 123,
   access_hash: '...'
}
```

**Comment by leonerd** [comment]
Ah excellent, thanks @goodmind - that does the trick.
Shall I make an addition into the main `README.md` to explain that general idea?

**Comment by zerobias** [comment]
Yes, of course)

Also, already implemented arguments with defaults - if you omit number argument, it becomes zero, string will be `' '` and complicated type such as [InputPeer](https://tjhorner.com/tl-schema/type/InputPeer) will cast to inputPeer**Empty** - one of its values with *-Empty* in the name (it's always empty object)

**Comment by goodmind** [comment]
Now covered here: https://github.com/zerobias/telegram-mtproto/wiki/FAQ#how-to-send-objects
