### ISSUE TITLE
While auth.sendCode error on channel not found and channel.callMEthod

### ISSUE THREAD

**Issue by javeedrahman** [zerobias/telegram-mtproto#47]
Question::
When i am trying to sendCode::
i am getting following error to add channel, i am create a channel and created a channel url to
 **client.setChannel(channel)** but i am getting error.

Uncaught (in promise) TypeError: channel.callMethod is not a function
    at TelegramClient.callApi 
  at connection.connect.then.then

Any suggestion should channel need to be added? mandatory?
and why is used for?

Thanks in advance.

**Comment by goodmind** [comment]
What version of library are you using?

**Comment by javeedrahman** [comment]
i have installed it from npm --> npm i telegram-mtproto and version is "telegram-mtproto": "^1.0.5".

Should i need to get from github ?

**Comment by wfjsw** [comment]
use telegram-mtproto@beta or telegram-mtproto@alpha .

**Comment by javeedrahman** [comment]
Okay thank you, I have starts using telegram-mtproto@beta, when i run the code for auth.sendCode and auth.singIn i am getting the following error can you please help. I have created my app in telegram recently. (two days before) but its saying Api_id_invalid.

Object
code:400
description:"CODE#400 API_ID_INVALID"
originalError:Objecttype:"API_ID_INVALID"__proto__:Object
