### ISSUE TITLE
App API ID is invalid

### ISSUE THREAD

**Issue by javeedrahman** [zerobias/telegram-mtproto#48]
Hi all,

I have create an app in https://my.telegram.org/apps, I have given, App Title, Short name, URL, Platform as Desktop and description.

I have got api_id, api_hash etc, When i am trying to implement in code, i am getting API_ID_INVALID, I have tried with different API_ID but same result. Searched hard no luck.

![api_id_error](https://cloud.githubusercontent.com/assets/3214829/25770637/6e0eebe2-3258-11e7-9f33-e9882476b49b.png)

Any help highly appreciated.
Thanks in advance.

**Comment by zerobias** [comment]
Does the connection work with [these](https://github.com/zerobias/telegram-mtproto/blob/master/examples/login.js#L10) keys?

Seems like telegram carelessly rejects a lot of keys

**Comment by javeedrahman** [comment]
Its working fine with [these](https://github.com/zerobias/telegram-mtproto/blob/master/examples/login.js#L10) links

**Comment by goodmind** [comment]
What methods are you calling?

**Comment by javeedrahman** [comment]
Here is my code::

const { MTProto } = require('telegram-mtproto')

const phone = {
  num : '************',
  code: '*****'
}

const config = {
  id : *****,
  hash: '***************************'
}

const api = {
  layer          : 57,
  initConnection : 0x69796de9,
  api_id         : ******
}

const server = {
  dev: true //We will connect to the test server.
}           //Any empty configurations fields can just not be specified

const client = MTProto({ server, api })

async function connect(){
  const { phone_code_hash } = await client('auth.sendCode', {
    phone_number  : phone.num,
    current_number: false,
    api_id        : config.id,
    api_hash      : config.hash
  })
  const { user } = await client('auth.signIn', {                      ---> Getting Error in this line (This method)
    phone_number   : phone.num,
    phone_code_hash: phone_code_hash,
    phone_code     : phone.code
  })

  console.log('signed as ', user)
}

connect()

**Comment by goodmind** [comment]
Well, I think that telegram just rejects new keys

**Comment by javeedrahman** [comment]
Any suggestion of solving this problem?

**Comment by zerobias** [comment]
@javeedrahman just use working keys (i.g. from webogram) :new_moon_with_face:

**Comment by javeedrahman** [comment]
Thank you :)
