### ISSUE TITLE
PHONE_NUMBER_UNOCCUPIED.

### ISSUE THREAD

**Issue by hengkyz** [zerobias/telegram-mtproto#51]
i try to sign after i receive the phone_hash_code that i got from sendCode method
but why it is returning error 400 PHONE_NUMBER_UNOCCUPIED.
any idea?

**Comment by wfjsw** [comment]
I guess you need `auth.signUp` instead of `auth.signIn`

**Comment by zerobias** [comment]
Yes, I think that your number just not registered. Check out your config; probably you try to connect to dev server

**Comment by hengkyz** [comment]
it should be registered coz i can sign in if i use webogram client using my number,

**Comment by wfjsw** [comment]
set `dev: true` to `dev: false`.

**Comment by crypto-ali** [comment]
Is there any other solution to this? I'm getting the same error but I'd like to be on dev and not production as I'm still testing my app.

**Comment by Defuera** [comment]
Ok, I found a solution. You have to specify all TdLibParameters correctly. I don't know which parameter were causing the problem, but this setup fixed if for me (android project):
```
        parameters.useTestDc = false
        parameters.databaseDirectory = appFolder
        parameters.filesDirectory = appFolder
        parameters.useFileDatabase = false
        parameters.useChatInfoDatabase = false
        parameters.useMessageDatabase = false
        parameters.useSecretChats = false
        parameters.apiId = 1111
        parameters.apiHash = "1111"
        parameters.systemLanguageCode = Locale.getDefault().isO3Language
        parameters.deviceModel = Build.MODEL
        parameters.systemVersion = Build.VERSION.RELEASE.toString()
        parameters.applicationVersion = "0.1"
        parameters.enableStorageOptimizer = true
        parameters.ignoreFileNames = true
```
