### ISSUE TITLE
contacts.importContacts

### ISSUE THREAD

**Issue by ardalanamini** [zerobias/telegram-mtproto#52]
i'm using version 2.2.8 and i get this error when i try to import contacts:
[8.557] Error undefined undefined 2 4
any help?

**Comment by ardalanamini** [comment]
1 week and no answer, thanks for help

**Comment by wfjsw** [comment]
That log is not really helpful.
Pull down the new code and try rerun with `DEBUG=*` 
A more detailed log should appear.

**Comment by ardalanamini** [comment]
i'm using webpack and it doesn't work with `DEBUG=*`

**Comment by zerobias** [comment]
@ardalanamini mtproto-logger is based on [debug](https://www.npmjs.com/package/debug#browser-support) library so this should work
```js
localStorage.debug = 'telegram-mtproto:*'
```

**Comment by ardalanamini** [comment]
the error i get refers to these:
`tl:type-buffer [writeInt]  8.557 +0ms
tl:type-buffer da30b32d +0ms 3660624685 contacts.importContacts[id]:int
tl:type-buffer [writeInt]  8.557 +0ms
tl:type-buffer 1cb5c415 +0ms 481674261 contacts[id]:int
tl:type-buffer [writeInt]  8.557 +0ms
tl:type-buffer 1 +0ms 1 contacts[count]:int`

**Comment by wfjsw** [comment]
Still nothing related. Please post the whole error message along with the stack trace.
