### ISSUE TITLE
Handling of `FILE_MIGRATE_x` errors

### ISSUE THREAD

**Issue by leonerd** [zerobias/telegram-mtproto#54]
Since `telegram-mtproto` attempts to transparently handle the `PHONE_MIGRATE_x` class of errors when calling `auth.sendCode`, it would be consistent for it to also handle the `FILE_MIGRATE_x` class of errors as occurs when you attempt to `uploads.getFile` on a location indicating a different `dc_id` from the one you're currently connected to.

Currently these are passed up to the caller, looking like:

```
Unhandled rejection (<{"code":303,"type":"FILE_MIGRATE_2","d...>, no stack trace)
```

Given as additionally, the `uploads.getFile` call is exempt from the usual updates-directing logic in the servers as most other API calls are, it should be possible to handle this by transparently creating new connections without further disturbing the updates mechanism, as currently alluded to by #53

**Comment by leonerd** [comment]
In the meantime, is there anything I can do manually, to handle these errors in my own code? E.g. can I create a new `MTProto` client instance directed towards a particular DC?

**Comment by zerobias** [comment]
@leonerd 
I will check my sources; it seems I just did not publish this functionality, I recently worked on it.

By the way, all errors are intercepted [here](https://github.com/zerobias/telegram-mtproto/blob/feature/mtproto3/packages/telegram-mtproto/src/service/networker/index.js#L913) and immediately emits into [this](https://github.com/zerobias/telegram-mtproto/blob/feature/mtproto3/packages/telegram-mtproto/src/event/stream-bus.js#L124) stream (`client.bus.rpcError`)

To the note, `stream.observe ≈ stream.onValue`


Incoming object type https://github.com/zerobias/telegram-mtproto/blob/feature/mtproto3/packages/telegram-mtproto/src/event/stream-bus.js#L353
