### ISSUE TITLE
Can I use this library on a js website?

### ISSUE THREAD

**Issue by onsamp** [zerobias/telegram-mtproto#56]
**Can I use this library on a js website???**

I want to write a web application whether it is possible to use somehow these features on the html site

**Comment by goodmind** [comment]
Yes, use webpack

**Comment by onsamp** [comment]
Please help !!
Configure webpack

I'll be very grateful

**Comment by zerobias** [comment]
Okay, seems like we need to make webpack example

**Comment by onsamp** [comment]
а может можно както подключить его на сайт без webpack  можно ли както

**Comment by onsamp** [comment]
Can be connected to the site of its without the webpack

**Comment by onsamp** [comment]
я могу  оплатить вашу  работу  только плиз помогите  мне !

**Comment by onsamp** [comment]
I can pay your work only pliz help me

**Comment by onsamp** [comment]
dist path  for web

**Comment by onsamp** [comment]
crypto.js:55 CW error Event {isTrusted: true, type: "error", target: Worker, currentTarget: Worker, eventPhase: 2…} undefined

**Comment by onsamp** [comment]
crypto.js:38 GET http://localhost:3000/bundle/hash.worker.js 404 (Not Found)

**Comment by onsamp** [comment]
solved a problem

**Comment by Lord-Protector** [comment]
@onsamp seems like you haven't any experience in coding :D

**Comment by onsamp** [comment]
change mtproto2-browser.js:1463 change path

**Comment by onsamp** [comment]
@Lord-Protector оkay

**Comment by onsamp** [comment]
I solved the problem it was necessary to connect the file from the folder dist

**Comment by zerobias** [comment]
@onsamp Fantastic :smile:  I didn't even suspect that this version can actually work)
This is really an ancient build and I doubt that it really can work)

**Comment by onsamp** [comment]
на  работу  я  еще не проверил но оно  не выдает ошибок пока
