### ISSUE TITLE
Make 3.x current master branch

### ISSUE THREAD

**Issue by zerobias** [zerobias/telegram-mtproto#57]
The current [development](https://github.com/zerobias/telegram-mtproto/tree/feature/mtproto3) version has twice as many commits as master and a significant number of improvements and fixes; it's time to update the master branch

**Comment by wfjsw** [comment]
Also more docs plz

**Comment by OwnageIsMagic** [comment]
And what stops you from doing this?

**Comment by zerobias** [comment]
@OwnageIsMagic Some troubles with a network protocol; decided not to publish until it becomes stable and predictable. I have been working on it around the clock, but it will take me a bit more time to fix.

**Comment by dmitrdv** [comment]
Hi!
any news about merging? what is better to use master or mtproto3 branch?

**Comment by goodmind** [comment]
@dmitrdv use mtproto3

**Comment by sajjad-ser** [comment]
is there any plan for this?
