### ISSUE TITLE
mtproto2-browser.js use

### ISSUE THREAD

**Issue by onsamp** [zerobias/telegram-mtproto#58]
I use  mtproto2-browser.js 

You can example how you can initiate the client and send any request

**Comment by ali-mahmoodvand** [comment]
@onsamp please write one example

**Comment by onsamp** [comment]
I have not yet found the solution could not send more than one request from the browser js

**Comment by goodmind** [comment]
Please, use webpack

**Comment by onsamp** [comment]
![image](https://cloud.githubusercontent.com/assets/15706392/26788491/01a2f07c-4a16-11e7-9085-47045ae9b2a6.png)

**Comment by zerobias** [comment]
@onsamp Will make valid independent browser build today

**Comment by onsamp** [comment]
@zerobias Okay thank you very much

**Comment by zerobias** [comment]
Now you can include actual `mtproto-browser` directly in script tag

**Comment by lollita** [comment]
I would a html example to login and get notified new messages.

**Comment by sprkweb** [comment]
Hello. I have not found this file in any telegram-mtproto version from npm since 6th June (3.0.8, 3.1.2, 3.1.3). Is it my mistake?
