### ISSUE TITLE
How to call api-methods with the vector in args?

### ISSUE THREAD

**Issue by FragsterAt** [zerobias/telegram-mtproto#6]
such as https://core.telegram.org/method/contacts.importContacts

i try this code:

```
              let contact = {
                client_id: 1, //long
                phone: 'phone', //string
                first_name: 'name', //string
                last_name: 'name' //strings
              };
              let cont = new tl.TypeVector({type: 'InputContact', list: [contact]});
              return client.callApi('contacts.importContacts', cont, true);

```
but have an error:
>TypeError: Cannot read property 'serialize' of undefined

**Comment by goodmind** [comment]
You should use `tl.InputContact` constructor for `contact`

**Comment by FragsterAt** [comment]
@goodmind , folloving code generate an error
`c1 = new client.schema.type.InputPhoneContact(contact);`

> undefined:4
> 	this.constructor.util._extend(this, opts.props);
> 	                     ^
> 
> TypeError: Cannot read property '_extend' of undefined
>     at Object.eval [as InputPhoneContact] (eval at createConstructor (/home/antonio/work/shedsender/shedsender/node_modules/telegram-mtproto/lib/tl/builder/constructor-builder.js:100:27), <anonymous>:4:23)

**Comment by FragsterAt** [comment]
>     at Object.eval [as InputPhoneContact] (eval at createConstructor (///node_modules/telegram-mtproto/lib/tl/builder/constructor-builder.js:100:27), <anonymous>:4:23)
>     at Object.<anonymous> (///importContacts.js:93:25)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)

**Comment by FragsterAt** [comment]
this is also wrong :(
```
let contact = {
                client_id: 1, //long
                phone: '12345678901', //string
                first_name: 'name', //string
                last_name: 'name' //strings
              };
let cont = new tl.TypeVector({type: 'InputContact', list: ([contact]).map((elem) => {
		return new client.schema.type.InputPhoneContact(elem);
	})});
			return client.callApi('contacts.importContacts', {contacts: cont, replace: true});
```

**Comment by zerobias** [comment]
Hi. Currently, I'm doing a new API for such cases, because current one came from 2014 and it's really buggy and unsound.

**Comment by zerobias** [comment]
I will upload new module within two or three days, stay tuned

**Comment by FragsterAt** [comment]
@zerobias Hello! I saw a lot of commits. They have a solution to my problem? Version updated in the NPM, or better to clone the repository in my project? (This involves some problems when I deploy an application on the production server)

**Comment by FragsterAt** [comment]
@goodmind @zerobias Guys, documentation is very important thing!
the right way to create vectors for requests is pass object with 'props' property:
			let cont = new tl.TypeVector({type: 'InputContact', list: ([contact]).map((elem) => {
					return new client.schema.type.InputPhoneContact({props:elem});
				})});
the right way to pass parameters to the call - object with properties equal to the parameter names from api.telegram.org
also bug with non latin characters is present https://github.com/enricostara/telegram.link/issues/34 ...

Unfortunately, I'm new to git and I do not know how to do pull request for README.md and bugfix for non-Latin characters in strings, so please do it yourself!

**Comment by goodmind** [comment]
There is fix for this in https://github.com/goodmind/telegram-tl-node/commit/66613a891f65dfe5af3214d5f9d0af8f63f22590. We need to just merge some fixes in @zerobias's version, but we are dropping working on @enricostara's version and forked https://github.com/zhukov/webogram to https://github.com/zerobias/telegram-mtproto/tree/mtproto2. I agree with you about documentation but we want to make [treact](https://github.com/goodmind/treact) works firstly

**Comment by goodmind** [comment]
@FragsterAt non-latin characters fixed in https://github.com/zerobias/telegram-mtproto/commit/e476c5c3af62d49c165a5f50f5f2b627595137f2
