### ISSUE TITLE
example of session storage

### ISSUE THREAD

**Issue by elyas74** [zerobias/telegram-mtproto#61]
Is there any example for saving sessions or something like this?

**Comment by goodmind** [comment]
Well, there are two issues about this #59 and #27

**Comment by zerobias** [comment]
I'm made separated plugin for saving sessions
https://github.com/zerobias/telegram-mtproto/blob/feature/mtproto3/packages/telegram-mtproto/test/node.test.js#L33

Or you can implement `AsyncStorage` https://github.com/zerobias/telegram-mtproto/issues/27

**Comment by zerobias** [comment]
Also, look at `mtproto-beam` https://github.com/zerobias/telegram-mtproto/blob/feature/mtproto3/packages/mtproto-beam/src/client.js#L4

**Comment by elyas74** [comment]
I install `mtproto-storage-fs` but when using it(require it), I got this error :
`Error: Cannot find module 'mtproto-storage-fs'`

what should I do?

**Comment by zerobias** [comment]
My fault; made the wrong build.  `mtproto-storage-fs@0.1.7` should be ok

**Comment by elyas74** [comment]
it works, thanks.

I don't know I should create a new issue or not, but the question is , How can we handle many users session? for example we have 20 users and want to choose witch one of them we want to be active and call methods.

**Comment by adplaygit** [comment]
@elyas74 

const client1 = MTProto({server: server, api: api, app:appStorage1});
const client2 = MTProto({server: server, api: api, app:appStorage2});
const client3 = MTProto({server: server, api: api, app:appStorage3});
...

**Comment by FragsterAt** [comment]
please help me :)

https://gist.github.com/FragsterAt/b706266676d7e791f25dc00448efb558

session storage just not working (file is empty) :(
also need help with my app_id - if I use it, I have 400 error "Wrong app Id"

package.json:
```
    "mtproto-storage-fs": "^0.1.8",
    "telegram-mtproto": "^2.2.2",
```

**Comment by elyas74** [comment]
[this](https://gist.github.com/elyas74/2df7e667a70a44f749efe3c3c99c7567) is a working example that can handle many storage when u init it with different phone numbers :
```
"telegram-mtproto": "3.0.6"
"mtproto-storage-fs": "^0.1.8"
```

I hope it help u.

**Comment by zerobias** [comment]
@FragsterAt We discussed this earlier; it seems that telegram just rejects any new tokens, so I'm going to remove any warnings about them from code. Because if Telegram doesn't fulfill its duties, we also can ignore it too.

Also, 3.0.6 really seems to be better, than your current version

**Comment by FragsterAt** [comment]
@elyas74 thanks! problem was:
`MTProto({ server, api, store });`
correct code:
`MTProto({ server: server, api: api, app: store });`
that js syntax sugar is white death sometimes :)

**Comment by FragsterAt** [comment]
when i try to use saved sessions, i get 
`{ Error: AUTH_RESTART`
error in console.
also, i use my own [simple store](https://gist.github.com/FragsterAt/941ffda347b42ae3d689ac1e3a0c9486), it will use database as storage finally, now it is "in memory storage": 

let session = JSON.parse('{...here data from prev run :)...}');
storage.loadData(session);
const telegram = MTProto({app: {storage}});
telegram('contacts.getContacts', {
      hash: '' // where I can get it?
    });
  }).then(contacts => {
    console.log('contacts', contacts);
    console.log(JSON.stringify(telegram.storage.saveData()));
    process.exit();

**Comment by FragsterAt** [comment]
this is my test.js https://gist.github.com/FragsterAt/abfc045c4e7064afef28701be12f908e

**Comment by FragsterAt** [comment]
@goodmind @zerobias  can you help me? same error with mtproto-storage-fs :(

**Comment by zerobias** [comment]
@FragsterAt I'm I am fixing this problem in the third branch; I think that next week you will be able to use it

**Comment by FragsterAt** [comment]
@zerobias still have "Error: AUTH_RESTART" with session storage in version 3.1.3, is there any workaround?

**Comment by dundas** [comment]
@elyas74 Thanks for your example. I'm still struggling to get a code example to work. Could you share sample code that loads the init and makes a call?

Thanks!

**Comment by dundas** [comment]
@FragsterAt I checked your file. Were you ever able to get this to work? Thanks for any pointers!

**Comment by zerobias** [comment]
@dundas current plugin version `mtproto-storage-fs@^0.3.1` is better solution, I replace all error-prone async operations with simple sync IO
I made test to ensure that it really works https://github.com/zerobias/telegram-mtproto/blob/feature/mtproto3/packages/telegram-mtproto/test/node.test.js#L152

**Comment by dundas** [comment]
Thanks @zerobias working to implement this now. Came across this error: https://github.com/zerobias/telegram-mtproto/issues/107

Seems like units isn't defined in this file. Is this a bug or am I missing something. 

Cheers.
