### ISSUE TITLE
Server side support

### ISSUE THREAD

**Issue by arthot** [zerobias/telegram-mtproto#64]
Hi, I'm wondering, does this project has any plans to continue support of server side, because telegram-mtproto v1 use to handle this. This question may looks strange because you already have test which works on node `telegram-mtproto/test/node.test.js`, but there are 2 points preventing from normal usage on server side:

- `"dependencies": { "worker-loader": "^0.8.0" }`, with ```"peerDependencies": {
    "webpack": ">=0.9 <2 || ^2.1.0-beta || ^2.2.0"
  }``` 
- es6 import/export

It's not a problem for client-side projects which are usually build with babel/webpack, but on server side vanilla es6/es5 without babel is still quite popular solution. 

Initially I thought, that removing webpack dependency and renaming dist/mtproto2-browser.js to dist/mtproto2.js will be enough, but in dev brach, which soon will be master `dist` folder is removed and plug-in "worker-loader" persists.

I believe it's good time to make such decision before new major version, because it's seems like now node js ecosystem doesn't have good telegram client library for server usage since nowadays [telegram.link](https://github.com/goodmind/telegram.link) is deprecated.

**Comment by FragsterAt** [comment]
+1 for server side use

**Comment by wfjsw** [comment]
If you want to work directly on the code you'll have to npm prepublish it

**Comment by zerobias** [comment]
worker-loader provides webpack building; I will throw it off as soon as I get to this code part.

Just for the note: during the release building, source code goes through several stages, whereby final file list in npm differs from what you see in a repository
Mtproto already contains pure node commonjs build and single browser bundle and chooses the version which fits your environment. You can easily use it in nodejs without any transpilation
```javascript
var MTProto = require('telegram-mtproto').MTProto;
```

**Comment by arthot** [comment]
Ok, so I've just checked it out, and
```
npm i webpack@2.2.0
npm i telegram-mtproto@beta
```
then
```
const MTProto = require('telegram-mtproto').MTProto;
```
is workable, because the package is pre-published in `lib` directory, so the point about es6 is not problem, but `webpack` dependency should be removed, because it blows out `node_modules`. Since you have such plans, you can rename this issue to "Remove direct dependency from webpack" and close this when it will be resolved. For now node packages ecosystem is in safe 😄

**Comment by goodmind** [comment]
@zerobias i think this can be closed?

**Comment by zerobias** [comment]
@goodmind sure
