### ISSUE TITLE
Error 401 SESSION_PASSWORD_NEEDED

### ISSUE THREAD

**Issue by Alavi1412** [zerobias/telegram-mtproto#73]
When I use login function and I entered the correct code, I got the following error

**Comment by goodmind** [comment]
@Alavi1412 why you don't look at exampels

**Comment by goodmind** [comment]
https://github.com/zerobias/telegram-mtproto/blob/feature/mtproto3/examples/login-2fa.js

**Comment by Alavi1412** [comment]
I have used the exapmle and got the following error.
I have solved it by disabling two step verification

**Comment by goodmind** [comment]
lol
