### ISSUE TITLE
how to use constructor?

### ISSUE THREAD

**Issue by Alavi1412** [zerobias/telegram-mtproto#76]
I want to use `channels.getMessages` method but when I use this:
```js
const inputChannel = {
      channel_id:  10454142,
        access_hash: '14600763172708131606'
    };

    const message = await client('channels.getMessages', {
        channel: inputChannel,
        id: [5]
    });
```
I got `Error: No predicate undefined found` .
How can I use constructors to create a inputChannel?

I have another question.
I found the TL-Schema for Telegram API - Layer 71 [here](https://tjhorner.com/tl-schema/) but I don't know How to update my package from layer 51 to 71?

**Comment by goodmind** [comment]
What version of library are you using? In previous issue asked not about layer

**Comment by Alavi1412** [comment]
this:
"telegram-mtproto": "^2.2.2"

**Comment by Alavi1412** [comment]
@goodmind 
Is there anything wrong with my code?

**Comment by goodmind** [comment]
Update to latest version with `npm i telegram-mtproto@alpha`. And where you got `access_hash`?

**Comment by Alavi1412** [comment]
@goodmind 
thankyou.
with this method:
https://tjhorner.com/tl-schema/method/contacts.resolveUsername

**Comment by Alavi1412** [comment]
problem still exist and when I updated to last version, the speed became very low. so I go back to 2.2.2 version.

**Comment by goodmind** [comment]
@Alavi1412 
```js
const inputChannel = {
  _: 'inputChannel',
  channel_id:  10454142,
  access_hash: '14600763172708131606'
};

const message = await client('channels.getMessages', {
  channel: inputChannel,
  id: [5]
});
```

**Comment by goodmind** [comment]
Now covered it here: https://github.com/zerobias/telegram-mtproto/wiki/FAQ#how-to-send-objects
