### ISSUE TITLE
avoiding send Message method each time

### ISSUE THREAD

**Issue by Alavi1412** [zerobias/telegram-mtproto#79]
I want to get `auth_key` for my users so when I restart the app, my users don't need to receive a code and enter it again.
But I don't know how to do this.

**Comment by goodmind** [comment]
https://github.com/zerobias/telegram-mtproto/blob/master/README.md#storage

**Comment by FragsterAt** [comment]
@goodmind this didn-t work (for me), I get AUTH_RESTART error on version 3.1.3

**Comment by goodmind** [comment]
@FragsterAt `AUTH_RESTART` isn't related to this

**Comment by FragsterAt** [comment]
@goodmind but storage is useless, if it can't be used for saving authorization
