### ISSUE TITLE
how should use vectors?

### ISSUE THREAD

**Issue by Alavi1412** [zerobias/telegram-mtproto#80]
@goodmind 
I want to get members of a channel using this:

```
    const channel = await client('channels.getChannels', {
        id: [{
            _: "inputChannel",
            id: 1130447105,
            access_hash: '9208645683267878297'
        }]
    });
    console.log(channel);
```

but it says:
`NEED_CHAT_INVALID`
What is need_chat?

**Comment by goodmind** [comment]
@Alavi1412 it's weird, show me mtproto connection options

**Comment by wfjsw** [comment]
@Alavi1412 He means the latter `id`
https://github.com/wfjsw/telegram-core-docs/blob/master/constructor/inputChannel.md

**Comment by goodmind** [comment]
@wfjsw also tjhorner works on new docs

**Comment by wfjsw** [comment]
oops new layer 71.
I want some API description in clear text though. Sadly I don't have time to write that.
