### ISSUE TITLE
Uncaught TypeError: Failed to execute 'postMessage' on 'Window': 2 arguments required, but only 1 present.

### ISSUE THREAD

**Issue by ehsan89** [zerobias/telegram-mtproto#85]
I updated to version 3.2.4 and I get the following error on startup of the application:

> worker.js:8 Crypto worker registered
> worker.js:4 Crypto worker registered
> worker.js:35 Uncaught TypeError: Failed to execute 'postMessage' on 'Window': 2 arguments required, but only 1 present.
>     at Object../node_modules/telegram-mtproto/es/worker.js (worker.js:35)
>     at __webpack_require__ (bootstrap e834d5e5360582ac604a:659)
>     at fn (bootstrap e834d5e5360582ac604a:85)
>     at Object../node_modules/telegram-mtproto/es/crypto.js (crypto.js:48)
>     at __webpack_require__ (bootstrap e834d5e5360582ac604a:659)
>     at fn (bootstrap e834d5e5360582ac604a:85)
>     at Object../node_modules/telegram-mtproto/es/service/chain/encrypted-message.js (encrypted-message.js:1)
>     at __webpack_require__ (bootstrap e834d5e5360582ac604a:659)
>     at fn (bootstrap e834d5e5360582ac604a:85)
>     at Object../node_modules/telegram-mtproto/es/state/epic/net-request.js (net-request.js:1)
>     at __webpack_require__ (bootstrap e834d5e5360582ac604a:659)
>     at fn (bootstrap e834d5e5360582ac604a:85)
>     at Object../node_modules/telegram-mtproto/es/state/epic/index.js (index.js:1)
>     at __webpack_require__ (bootstrap e834d5e5360582ac604a:659)
>     at fn (bootstrap e834d5e5360582ac604a:85)
>     at Object../node_modules/telegram-mtproto/es/state/core.js (core.js:1)
>     at __webpack_require__ (bootstrap e834d5e5360582ac604a:659)
>     at fn (bootstrap e834d5e5360582ac604a:85)
>     at Object../node_modules/telegram-mtproto/es/index.js (index.js:1)
>     at __webpack_require__ (bootstrap e834d5e5360582ac604a:659)
>     at fn (bootstrap e834d5e5360582ac604a:85)
>     at Object../src/config/constants.js (constants.js:1)
>     at __webpack_require__ (bootstrap e834d5e5360582ac604a:659)
>     at fn (bootstrap e834d5e5360582ac604a:85)
>     at Object../src/components/Auth/Login.js (App.js:163)

**Comment by zerobias** [comment]
Oh, weird, will fix as soon as possible.

**Comment by zerobias** [comment]
Made fix in `3.2.7`, needs confirmation

**Comment by ehsan89** [comment]
Seems like there's another problem now:

> Uncaught TypeError: TmpWorker is not a constructor
>     at Object../node_modules/telegram-mtproto/es/crypto.js (crypto.js:50)
>     at __webpack_require__ (bootstrap b12cce1e55afd7fea986:659)
>     at fn (bootstrap b12cce1e55afd7fea986:85)
>     at Object../node_modules/telegram-mtproto/es/service/chain/encrypted-message.js (encrypted-message.js:1)
>     at __webpack_require__ (bootstrap b12cce1e55afd7fea986:659)
>     at fn (bootstrap b12cce1e55afd7fea986:85)
>     at Object../node_modules/telegram-mtproto/es/state/epic/net-request.js (net-request.js:1)
>     at __webpack_require__ (bootstrap b12cce1e55afd7fea986:659)
>     at fn (bootstrap b12cce1e55afd7fea986:85)
>     at Object../node_modules/telegram-mtproto/es/state/epic/index.js (index.js:1)
>     at __webpack_require__ (bootstrap b12cce1e55afd7fea986:659)
>     at fn (bootstrap b12cce1e55afd7fea986:85)
>     at Object../node_modules/telegram-mtproto/es/state/core.js (core.js:1)
>     at __webpack_require__ (bootstrap b12cce1e55afd7fea986:659)
>     at fn (bootstrap b12cce1e55afd7fea986:85)
>     at Object../node_modules/telegram-mtproto/es/index.js (index.js:1)
>     at __webpack_require__ (bootstrap b12cce1e55afd7fea986:659)
>     at fn (bootstrap b12cce1e55afd7fea986:85)
>     at Object../src/config/constants.js (constants.js:1)
>     at __webpack_require__ (bootstrap b12cce1e55afd7fea986:659)
>     at fn (bootstrap b12cce1e55afd7fea986:85)
>     at Object../src/components/Auth/Login.js (App.js:163)
>     at __webpack_require__ (bootstrap b12cce1e55afd7fea986:659)
>     at fn (bootstrap b12cce1e55afd7fea986:85)
>     at Object../src/App.js (fetch.js:461)

**Comment by goodmind** [comment]
this is related to `worker-loader` maybe? @zerobias

**Comment by zerobias** [comment]
Hmm, maybe 🤔  Strange error

**Comment by goodmind** [comment]
@zerobias this should be fixed in 3.2.10?

**Comment by zerobias** [comment]
Maybe

**Comment by Tidhy** [comment]
不知道是什么问题，同样遇到了
