### ISSUE TITLE
Using TCP tunneling connection for faster updates

### ISSUE THREAD

**Issue by JackPoteYes** [zerobias/telegram-mtproto#87]
It is written that Tl's api supports TCP tunneling instead of HTTP requests, in order to receive any new message ASAP. So no need to request the server in order to update the messages.
Where to put this configuration parameter ?
Any example ?

I need to read a message in a known interval of time, where each milisecond counts.

Thank you

**Comment by wfjsw** [comment]
Duplicate of #1
