### ISSUE TITLE
PHONE_CODE_INVALID

### ISSUE THREAD

**Issue by ltyu** [zerobias/telegram-mtproto#88]
I'm constantly getting this error: 
[5.091] Error 400 PHONE_CODE_INVALID 2 1
{ code: 400,
  type: 'PHONE_CODE_INVALID',
  description: 'CODE#400 PHONE_CODE_INVALID',
  originalError:
   { _: 'rpc_error',
     error_code: 400,
     error_message: 'PHONE_CODE_INVALID' } }

Everytime I run this I get a new code through my phone in which i use for the next run which gives the same error. I'm running 2.2.2 

Heres my code:

```js
const {MTProto} = require('telegram-mtproto')

const phone = {
	num : '+xxxxxxx',
	code: '12345'
}

const api = {
	layer          : 57,
	initConnection : 0x69796de9,
	api_id         : xxxxxx,
	invokeWithLayer: 0xda9b0d0d,
  app_version    : '1.0.1',
  lang_code      : 'en'
}

const server = {
	webogram: true,
	dev: false //We will connect to the test server.
}           //Any empty configurations fields can just not be specified

const client = MTProto({ server, api })

async function connect(){
	try {
		const { phone_code_hash } = await client('auth.sendCode', {
			phone_number  : phone.num,
			current_number: false,
			api_id        : xxxxxxxx,
			api_hash      : 'xxxxxxx'
		})
		const { user } = await client('auth.signIn', {
			phone_number   : phone.num,
			phone_code_hash: phone_code_hash,
			phone_code     : phone.code
		})

		console.log('signed as ', user)
	} catch(error) {
		console.error(error);
	}
}

connect()
```

**Comment by morlz** [comment]
I was helped by a return to 2.2.1

**Comment by ltyu** [comment]
@morlz Thanks for you response. Using 2.2.1 gave the the error auth_key_unregistered

**Comment by goodmind** [comment]
@ltyu this is because auth between different versions is incompatible

**Comment by ltyu** [comment]
@goodmind How do make the versions compatible?

**Comment by goodmind** [comment]
Try to relogin

**Comment by rolldone** [comment]
any solution, my problem are same

**Comment by goodmind** [comment]
Do you still encountering this problem?

**Comment by Roy5000** [comment]
Problem is still there, I have version 2.2.1 installed and also receive the PHONE_CODE_INVALID message. Everytime I run this I get a new code through my phone in which i use for the next run which gives the same error.

@ltyu did you found a solution for your issue?

ErrorMessage:
`[2.084] Error 400 PHONE_CODE_INVALID 2 2
(node:8844) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): #<Object>
(node:8844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
