### ISSUE TITLE
TypeError: No method name messages.SentMessage found

### ISSUE THREAD

**Issue by DucNguyen0611** [zerobias/telegram-mtproto#97]
I want to send message to channel. But i got the error "No method name messages.SentMessage found".
I am using telegram-mtproto 3.2.11.

**Comment by wfjsw** [comment]
use messages.sendMessage
https://schema.horner.tj/#!/method/messages.sendMessage

**Comment by DucNguyen0611** [comment]
It wasn't worked.
@wfjsw you have the same issue at #25, how did you fix it?

**Comment by goodmind** [comment]
@DucNguyen0611 please provide code, not only error

**Comment by goodmind** [comment]
also read FAQ https://github.com/zerobias/telegram-mtproto/wiki/FAQ#how-to-send-objects

**Comment by DucNguyen0611** [comment]
I used code in examples folder and add sendMessage function to chat-history

const sendMessage = async (chat, mess) => {
    await telegram('messages.SentMessage', {
      peer: {
        _          : 'inputPeerChannel',
        channel_id : chat.id,
        access_hash: chat.access_hash
      },
      message: mess
    })
}

**Comment by goodmind** [comment]
Not `messages.SentMessage` but `messages.sendMessage` 

@wfjsw already helped you

**Comment by DucNguyen0611** [comment]
Thank you
