### ISSUE TITLE
Auth_key_empty

### ISSUE THREAD

**Issue by Alavi1412** [zerobias/telegram-mtproto#98]
I got the `Auth_key_empty` error for using some countries.
```js
await client.storage.clear();

    let phone = await inputField.inputField('phone');

    const  phone_code_hash  = await client('auth.sendCode', {
        phone_number  : phone,
        current_number: true,
        api_id        : 166413,
        api_hash      : '89c7f8a6b55d6b50b078203405da032e'
    });

    const code = await inputField.inputField('code');

    const user = await client('auth.signUp', {
        phone_number   : phone,
        phone_code_hash: phone_code_hash.phone_code_hash+ "",
        phone_code     : code + "",
        first_name     : "hassan"
    });
    const log = await client('auth.signIn', {
        phone_number   : phone,
        phone_code_hash: phone_code_hash.phone_code_hash+ "",
        phone_code     : code + ""
    });

    await client.storage.save();
```

This code works well for Iran or Russia but throw error for united_states or china.
What is the problem

**Comment by goodmind** [comment]
What error you get?

**Comment by 2012mjm** [comment]
i have similar problem

**Comment by 2012mjm** [comment]
Use version 3.2.11
npm i -S telegram-mtproto@alpha

**Comment by flavianohonorato** [comment]
I had this same problem, I updated the version with `npm i -S telegram-mtproto @ alpha` and now I get the following error when I use the` sendInvites () `endpoint:
<img width="765" alt="screen shot 2018-01-29 at 07 53 54" src="https://user-images.githubusercontent.com/4780299/35506882-a59fa71a-04c9-11e8-99b3-5ed13d862beb.png">
