### ISSUE TITLE
Server salt expired

### ISSUE THREAD

**Issue by wfjsw** [zerobias/telegram-mtproto#99]
The session persistent works for a few minutes at first, but then I received some errors telling me the server salt has expired.

Storage engine: mtproto-storage-fs

**Comment by tulir** [comment]
I think I'm getting the same problem. About an hour after logging in, the connection stops working. When I enabled debug messages, it spammed something about expired server salts.
I'm using a custom storage engine and restarting works just fine as long as it's less than an hour since login.
I can provide the debug logs if needed.

**Comment by tulir** [comment]
I'm fairly certain that updating the server salts breaks at 564779c5afb0cf9fe528b668422800685934d5d2. Even before that commit, the updated salts don't seem to reach the storage engine, but they are still used internally and the connection works fine.

**Comment by 2012mjm** [comment]
I have same problem https://github.com/zerobias/telegram-mtproto/issues/121

**Comment by 2012mjm** [comment]
I have used the _alpha version_ and the problem of China's phone numbers in Iran has been solved for me, but the problem below has come to me that did not occur in the _beta version_.

Everything works great, but I can not authenticate after I stopped the command line and after 10 minutes I run the project again.

I get an **bad_server_salt** error

```
single-handler [Bad server salt]  9.010 +0ms
  single-handler { flags: 
  single-handler    { api: false,
  single-handler      inner: false,
  single-handler      container: false,
  single-handler      incoming: true,
  single-handler      methodResult: false,
  single-handler      body: true,
  single-handler      error: false },
  single-handler   incoming: { timestamp: 1511471434226 },
  single-handler   body: 
  single-handler    { _: 'bad_server_salt',
  single-handler      bad_msg_id: '6491720375343291572',
  single-handler      bad_msg_seqno: 72,
  single-handler      error_code: 48,
  single-handler      new_server_salt: '10292941774626279723' },
  single-handler   uid: '44142efe',
  single-handler   id: '6491720107758749697',
  single-handler   seq: 0,
  single-handler   session: [ 159, 220, 37, 114, 16, 224, 223, 101 ],
  single-handler   dc: 1 } +0ms
  single-handler [protocol error][code]  9.010 +1ms
  single-handler 48 +0ms
  single-handler [protocol error][message]  9.010 +0ms
  single-handler MT[48] ProtocolError: incorrect server salt +0ms
  single-handler [protocol error][description]  9.010 +0ms
  single-handler In this case, the bad_server_salt response is received with the correct salt, and the message is to be re-sent with it +0ms

 tl:reader INPUT[bad_server_salt][bad_msg_id]:long[low] 1818441268 +0ms
```

It also crashes in the loop and repeats the same error messages in debug

**Comment by 2012mjm** [comment]
I tested Beta and Alpha again
There was no problem with beta
I think that after a while, salt will expire and a new amount must be produced and replaced

**Comment by THROFHR** [comment]
Hi, I also encountered such a question, can I ask if there is a solution?
I use `npm install --save telegram-mtproto@alpha` @wfjsw @2012mjm

**Comment by tulir** [comment]
@THROFHR The last commit that works is 083d8c4cd096502e9c347eb1f4a4191ca939842a. If you don't want to manually clone and compile it, you can install `telegram-mtproto@3.2.7` for the closest release before that commit.

**Comment by AndreasGassmann** [comment]
I'm having exactly the same problem. Was anyone able to find a fix / workaround?

**Comment by tulir** [comment]
@AndreasGassmann You might want to read my reply right above yours...

**Comment by AndreasGassmann** [comment]
@tulir Thanks, I didn't see your reply just above mine. /s

Still looking for a fix other than downgrading to an older version.

**Comment by tulir** [comment]
I don't think there are any proper solutions other than actually fixing the library, but it'll probably take a while before anyone does that.

I just gave up and switched to Python, Telethon is well maintained and has an awesome API.

**Comment by Fuzzyma** [comment]
So somewhere in this huge commit with 10 changed files is the reason why this does not work anymore. Well - happy searching...
When I find some spare time I will try to find something
